benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/BenchmarkDriver.java, drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDevice.java, drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLKind.java, drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoIfCanonicalization.java, drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLObjectWrapper.java, drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java, examples/src/main/java/uk/ac/manchester/tornado/examples/compression/Huffman.java, examples/src/main/java/uk/ac/manchester/tornado/examples/compression/HuffmanTornadoDecoder.java, runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/RuntimeUtilities.java, runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoDataflowAnalysis.java, runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoPragmaUnroll.java, runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoReduceReplacement.java
I was reading through the code and found these redundant Boolean statements. I ran `make` command on my repo and compilation looks good and unit tests passed.
=> removed redundant conditional statements

unittests/src/main/java/uk/ac/manchester/tornado/unittests/tools/Exceptions/UnsupportedConfigurationException.java, unittests/src/main/java/uk/ac/manchester/tornado/unittests/tools/TornadoHelper.java, unittests/src/main/java/uk/ac/manchester/tornado/unittests/virtualization/TestsVirtualLayer.java
Unsupported configuration graceful handling.
Please have a look at this my proposal of a bit more graceful way of handling of unsupported hardware configurations in tests.
Thank you.
=> Multi–device tests refactoring.

CONTRIBUTIONS.md, assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
This patch provides:
* Updated list of OpenCL drivers supported
* Formatting conventions updated
=> Documentation updated

assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
Check TornadoVM with the latest Intel HD drivers for OpenCL. 
How to test? 
```bash
$ make tests
```
If integrated GPU is device 2:
``` bash
$ export HDGRAPHICS_ID=2
$ make test-hdgraphics
```
=> [docs] Intel OpenCL drivers update 

INSTALL.md, README.md, assembly/pom.xml, assembly/src/bin/tornadoLocalInstallMaven, assembly/src/docs/1_INSTALL.md, assembly/src/docs/CHANGELOG.md, assembly/src/docs/Releases.md, benchmarks/pom.xml, drivers/drivers-common/pom.xml, drivers/opencl-jni/pom.xml, drivers/opencl/pom.xml, drivers/pom.xml, drivers/ptx-jni/pom.xml, drivers/ptx/pom.xml, examples/pom.xml, matrices/pom.xml, pom.xml, runtime/pom.xml, tornado-annotation/pom.xml, tornado-api/pom.xml, unittests/pom.xml
=> [release] TornadoVM 0.9

assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
List of supported drivers updated
=> [docs] List of supported drivers updated

assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
[docs] New OpenCL driver for Linux supported
=> [docs] New OpenCL driver for Linux supported 

drivers/opencl-jni/src/main/cpp/source/OCLCommandQueue.cpp
We have observed that for some drivers (Intel iGPU), having a read/write call to the driver, and then calling `clWaitForEvents` can be much slower than just passing `CL_TRUE` always to the read/write.
The two solutions are equivalent but the latter can provide some speed-ups.
`make && make tests`
=> Change data transfers to be blocking by passing CL_TRUE instead of calling clWaitForEvents

assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
NVIDIA Driver 470.57.02 supported.
=> [docs] List of NVIDIA drivers supported updated

INSTALL.md
This PR provides fixes to some broken links that exist in the `Install.md` file.
=> Fix links in documentation

README.md, scripts/tornadoVMInstaller.sh
Thank you for contributing to TornadoVM. This template provides checkpoints before opening PR, and a template to be filled when submitting a PR on GitHub.
At first, **please check our code style and guidelines** for contributing to the project.
* Guidelines: [link](https://github.com/beehive-lab/TornadoVM/blob/master/CONTRIBUTING.md)
All PRs must be open to merge into the `develop` branch of TornadoVM. Please, do not push the PR into `master`.
All unittests must pass. Note that some unittests may fail depending on the driver and runtime used. 
They are listed in a white-list in the `tornado-test.py` script. 
```bash
$ make tests
```
TornadoVM currently supports two backends. When possible, please check that the new changes do not break any backend.
```bash
$ make
$ make tests
$ make …
```
=> Small typo in scripts path

.github/ISSUE_TEMPLATE/bug_report.md, .github/pull_request_template.md
This PR updates the Gihub templates for filing bugs and pull requests. 
None
Not applicable; 
Not applicable; 
Not applicable; 
Not applicable;
=> [docs-repo] Github templates updated

tornado-annotation/pom.xml
ASM lib dependency updated
```bash
make 
make tests
```
=> [update] ASM lib updated

docs/source/installation.rst
This PR updates documentation to include Pop!_OS  in the supported OSs.
=> [docs] Add Pop!_OS  as supported OS in docs

docs/source/unsupported.rst
The patch was provided by Tianyu Zuo
Fix the type in the documentation of the unsupported list of features.
=> [docs] documentation list of unsupported items fixed. 

docs/source/resources.rst
Update the list of online resources for TornadoVM. 
Not applicable
Not applicable
Not applicable
=> [docs] Update list of resources

README.md
Checking CLA
README Documentation updated
=> README documentation updated

pom.xml, tornado-annotation/pom.xml, tornado-api/pom.xml, tornado-assembly/pom.xml, tornado-benchmarks/pom.xml, tornado-drivers/drivers-common/pom.xml, tornado-drivers/opencl-jni/pom.xml, tornado-drivers/opencl/pom.xml, tornado-drivers/pom.xml, tornado-drivers/ptx-jni/pom.xml, tornado-drivers/ptx/pom.xml, tornado-drivers/spirv/pom.xml, tornado-examples/pom.xml, tornado-matrices/pom.xml, tornado-runtime/pom.xml, tornado-unittests/pom.xml
Set the version to 1.0.3-dev for the new development track.
```bash
$ make
$ tornado --version
version=1.0.3-dev
branch=track/1.0.3-dev
commit=188e3a4
Backends installed: 
- opencl
```
=> Dev-track version set to 1.0.3-dev

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLCodeCache.java, tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLProgram.java, tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/enums/OCLBuildStatus.java, tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/enums/OCLProgramBuildInfo.java
Build log for OpenCL fixed. 
There was an issue when the OpenCL build was not correct, the log string was not printed. 
```bash
make 
make tests
```
=> [jit][ocl] Debug and build kernel improved

tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/vectortypes/TestFloats.java
Minor refactor
n/ a.
```
make
make tests
```
=> Cleanup vector initialisation - tests

Jenkinsfile
This PR provides an update in Jenkinsfile which clears the first stage that was checking out a conflicting branch. Now the branches to be tested are configured in the Jenkins server.
=> [feat] Removed conflicts that prohibited the build of remote branches

CONTRIBUTING.md
Update the CONTRIBUTIONS page with the latest review process we have implemented in TornadoVM. 
n/ a.
This PR only changes the documentation.
=> [docs] Contributions page updated

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLCodeCache.java, tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLInstalledCode.java, tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java, tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java, tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/TaskMetaData.java
Remove old code and non necessary fields from the `AbstractMetaData` class. 
n/ a,
For each backend:
```bash
make tests
```
=> Cleanup AbstractMetaData class 

tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/TornadoBufferProvider.java
Prints action to be done by developers when TornadoVM raises OOM exception. This may be useful for  developers to understand what to do when such exceptions are raised. 
n/ a.
```bash
make tests
```
=> When TornadoVM raises OOM, it prints a possible action to fix it

docs/source/programming.rst
I believe we need localBarrier here because we do not modify global memory.
=> Too strict barrier

tornado-api/src/main/java/uk/ac/manchester/tornado/api/GridScheduler.java, tornado-api/src/main/java/uk/ac/manchester/tornado/api/plan/types/WithDynamicReconfiguration.java, tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix3DLong.java, tornado-assembly/src/bin/tornado-test, tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/MMwithBytes.java
This PR adds one of the recent unit-tests in the white list, in order to avoid stopping the Jenkins pipeline. The reason is that sometimes, depending on the GPU driver it may result in different precision output.
Additionally, I fixed the checkstyle issues.
```bash
```
=> Whitelisted unit-test & Checkstyle application

docs/source/installation.rst
This PR adds documentation for the configuration and installation of CUDA and Intel compute runtime for WSL and the configuration of TornadoVM for WSL. 
n/ a.
```bash
make docs
google-chrome docs/build/html/index.html
```
=> [docs] WSL installation and configuration added

bin/tornadovm-installer, pom.xml, tornado-annotation/pom.xml, tornado-api/pom.xml, tornado-assembly/pom.xml, tornado-assembly/src/bin/tornado-test, tornado-benchmarks/pom.xml, tornado-drivers/drivers-common/pom.xml, tornado-drivers/opencl-jni/pom.xml, tornado-drivers/opencl/pom.xml, tornado-drivers/pom.xml, tornado-drivers/ptx-jni/pom.xml, tornado-drivers/ptx/pom.xml, tornado-drivers/spirv/pom.xml, tornado-examples/pom.xml, tornado-matrices/pom.xml, tornado-runtime/pom.xml, tornado-unittests/pom.xml
Bump version to 1.1.0-dev in pom.xml and related files
n/ a.
```bash
make 
make tests
```
=> [develop-track] Bump version to 1.1.0-dev in pom.xml and related files

tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
Hotfix: compilation error after the last merge.
```bash
make 
make tests
```
=> [hotfix] executionFrame setter after merge

README.md
This PR fixes the links of two projects in the Acknowledgements.
=> [doc] fix project links in README

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java, tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/dynamic/TestDynamic.java
This patch is a refactor of the dynamic reconfiguration part and clean up of old code. 
n/ a.
```bash
tornado-test -V uk.ac.manchester.tornado.unittests.dynamic.TestDynamic
```
=> [cleanup] Dynamic reconfiguration refactored

README.md
This PR updates README with the latest help message of the `tornadovm-installer` script.
=> Update tornadovm-installer changes in README
