unittests/src/main/java/uk/ac/manchester/tornado/unittests/tasks/TestSingleTaskSingleDevice.java

Due to driver issues double is often not accepted on a device. Rewriting the test with float fixes this issue

Due to driver issues double values are often not accepted on a device.

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDriver.java

With the introduction of TornadoBailoutRuntimeException this exception should be used. The handling of this exception is in `TornadoTaskSchedule#addTask` and then via `bailout` flag in `schedule` method

#11 Fix TornadoVM crashes when no OpenCL devices are available - fixed

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoTaskSpecialisation.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/nodes/AbstractParallelNode.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/nodes/ParallelRangeNode.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/loops/TestLoops.java

The issue was that for expressions such as "<=", the `TornadoTaskSpecialization` phase was inserting the constant node outside the parallel range node.
```java
public static void forConstant01(int[] a, final int n) {
for (@Parallel int i = 0; i < n; i++) {
a[i] = 10;
}
}
```
The solution is that, for the cases in which the Parallel Range contains a PhiNode as value, we can inspect the condition of the loop-bound. If a constant node is found, we can perform node swapping between these two.
Github issue #21
```bash
$ tornado-test.py -V -pk --debug  uk.ac.manchester.tornado.unittests.loops.TestLoops#testForConstant02 
task info: s0.t0
platform          : NVIDIA CUDA
device            : GeForce GTX 1050 CL_DEVICE_TYPE_GPU (available)
dims              : 1
global work offset: [0]
global work …
```

[TP-21] Parallelization of loops with constant loop-bounds

---

assembly/src/docs/6_TORNADO_FLAGS.md
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLLowTier.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLMidTier.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java

For Xilinx FPGAs running OpenCL 1.0 we need to disable FMA optimizations.
Use the flag `-Dtornado.enable.fma=False`
This flag is enabled by default.
Github issue #24 (Public)

[fix] FMA optimizations can be disabled

---

drivers/opencl-jni/src/main/cpp/source/data_movers.c

We always force a clWaitForEvent with enqueued data moves (read and write) whilst we are pinning the array. 
After the unpin GC is free to move the buffer, potentially before written (enqueueWrite), or after buffer has moved (enqueueRead)

add clWaitForEvents to data_movers.c to avoid possible GC/OpenCL race

---

assembly/src/etc/tornado.properties
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OpenCL.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTX.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/Tornado.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/ScheduleMetaData.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/TaskMetaData.java

This update provides an option to specify default driver / device to be used for TaskSchedule when no per-task settings are present. Without this option DRIVER=0 and DEVICE=0 is always used, and it's necessary to set device for each concrete task within schedule.
The PR is related to the issue https://github.com/beehive-lab/TornadoVM/issues/58

VM-wide default driver/device for TaskSchedule.

---

unittests/src/main/java/uk/ac/manchester/tornado/unittests/common/TornadoTestBase.java

Fixes virtual device tests when selecting a different physical device: `tornado-test.py --ea --verbose -J"-Dtornado.unittests.device=0:1" `
Before, we had this stacktrace:
```
2021/03/29 09:24:14
Test: class uk.ac.manchester.tornado.unittests.virtual.TestVirtualDeviceKernel#testVirtualDeviceKernelCPU
Running test: [34mtestVirtualDeviceKernelCPU[0m ................ [31m [FAILED] [0m
\_[REASON] 1
java.lang.ArrayIndexOutOfBoundsException: 1
at uk.ac.manchester.tornado.drivers.opencl.OCLDriver.swapDefaultDevice(OCLDriver.java:112)
at uk.ac.manchester.tornado.drivers.opencl.OCLDriver.setDefaultDevice(OCLDriver.java:80)
at uk.ac.manchester.tornado.unittests.common.TornadoTestBase.before(TornadoTestBase.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
```

[fix] failing virtual devices tests when another device is selected

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLEvent.java

Minor fix. As reported in #52, the `ByteBuffer` in `OCLEvent` should be a non-static field.

[fix] ByteBuffer in the OCL event from static to non-static

---

runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoCoreRuntime.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVMConfig.java

Resolves #59 
JDK 8 and 11 
```bash
$ make tests
```

Unsafe access removed from TornadoVMConfig and use JVMCI metaAccessProvider instead

---

assembly/src/bin/tornado-test.py
assembly/src/docs/15_FAQ.md
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskSchedule.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/exceptions/TornadoTaskRuntimeException.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/common/TornadoTestBase.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/fails/RuntimeFail.java

Throw an exception when at least two tasks within the same task-scheduler have the same name. 
Developers much provide a unique task-id per task within the same task-scheduler, otherwise, TornadoVM will fail to obtain the right binary from the code cache. However, prior to this PR there was no exception or help to guide the user. 
Github issue #569 (Internal)
This is at the API level. So it should not matter the backend and the OS. 
```bash
$ tornado-test.py -V -pk --debug uk.ac.manchester.tornado.unittests.fails.RuntimeFail#test01
```
The test launches an exception `TornadoTaskRuntimeException` that is watched in the unit test.

Runtime error when two tasks have the same name

---

assembly/src/docs/TORNADOVM_TESTED_DRIVERS.md
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompiler.java

When using Lambdas, the `ResolvedJavaMethod` uses the `$` symbol as part of the method name. This causes a problem on AMD devices using the ROCm driver. 
This patch fixes the issue by replacing the `$` with a `_`.
- [] Yes
```bash
$ tornado --printKernel -ea -Dtornado.unittests.verbose=True -Xmx6g -Dtornado.recover.bailout=False -Dtornado.unittests.device=0:2 uk.ac.manchester.tornado.unittests.tools.TornadoTestRunner  uk.ac.manchester.tornado.unittests.functional.TestLambdas
```
Report using the ROCm driver: 2766.4 
```bash
==================================================
Unit tests report 
==================================================
{'[FAILED]': 0, '[PASS]': 375}
Coverage: 100.0%
==================================================
Total …
```

[CodeGen] Fix kernel name for Lambda Expressions

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFMANode.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFPBinaryIntrinsicNode.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFPTernaryIntrinsicNode.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFPUnaryIntrinsicNode.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLIntBinaryIntrinsicNode.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLIntTernaryIntrinsicNode.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLIntUnaryIntrinsicNode.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXFPBinaryIntrinsicNode.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXFPUnaryIntrinsicNode.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXIntBinaryIntrinsicNode.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXIntUnaryIntrinsicNode.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/analyzer/ReduceCodeAnalysis.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/MarkFloatingPointIntrinsicsNode.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/MarkIntIntrinsicNode.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/MarkIntrinsicsNode.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoFeatureExtraction.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoReduceReplacement.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsDoubles.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsFloats.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsIntegers.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsLong.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/tornadovmcontext/reductions/TestReductionsDoublesTornadoVMContext.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/tornadovmcontext/reductions/TestReductionsFloatsTornadoVMContext.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/tornadovmcontext/reductions/TestReductionsIntegersTornadoVMContext.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/tornadovmcontext/reductions/TestReductionsLongTornadoVMContext.java

TornadoMath functions supported in reduce operations. TornadoVM math
provides operations for floats and doubles, avoiding typecasting in the
OpenCL/PTX code.
This PR solves issue #79 (Public)
```bash
$ tornado-test.py -V -pk --debug uk.ac.manchester.tornado.unittests.reductions.TestReductionsFloats#testMaxReduction
```

Support for TornadoMath functions in reductions

---

drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/backend/PTXBackend.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXLIRGenerationResult.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXLIRGenerator.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PrintfNode.java

This PR cleans the `PTXLIRGenerationResult` and the related classes. We were using `.param` variables in the kernel only for `printf` calls. I realised we can pass `.reg` parameters instead, and therefore there is no need for a `paramTable` now.
Previous call to `printf`:
```
.global .b8 rbbArr0[28] = {116, 111, 114, 110, 97, 100, 111, 91, 37, 117, 44, 32, 37, 117, 44, 32, 37, 117, 93, 62, 32, 104, 101, 108, 108, 111, 10, 0};
st.local.s32    [rbiArr0], rsi0;
st.local.s32    [rbiArr0+4], rsi2;
st.local.s32    [rbiArr0+8], rsi3;
cvta.global.u64 rbd0, rbbArr0;                <-- convert global state space address to generic address space 
st.param.b64    [rbdParam0], rbd0;        <-- store generic address into .param variable
cvta.local.u64 rbd0, rbiArr0;
st.param.b64    [rbdParam1], rbd0; …
```

Remove redundant parameter table from the PTXLIRGenerator

---

drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXCodeCache.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXModule.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXScheduler.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXStream.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/PTXInstalledCode.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXCompilationResult.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXCompiler.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/tests/TestPTXTornadoCompiler.java

This PR decouples the `TaskMetaData` from the `PTXModule`.
The code cache will store `PTXModule`s and therefore also store `TaskMetaData`. If the same `PTXModule` is used for different tasks, then Tornado will use the task metadata from the cache (from the previous task) instead of the current task meta. This can break scheduling.
I don't think it's possible to replicate this bug with the current code cache strategy `PTXCodeUtil::buildKernelName`.

Decouple task meta from the PTXModule

---

drivers/ptx-jni/src/main/cpp/source/PTXModule.cpp
drivers/ptx-jni/src/main/cpp/source/PTXModule.h
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXCodeCache.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXModule.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/PTXInstalledCode.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoInstalledCode.java

The PTX modules from the code cache were never unloaded from the driver when the PTX device was reset. 
This PR fixes that.
Run the unit tests on the PTX backend. `TornadoTestBase::before` resets devices before each test.

Unload PTX/CUDA modules when resetting the code cache

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/plugins/PTXGraphBuilderPlugins.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
pom.xml
runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java

Graal performs inlining during bytecode parsing by default. Tornado does not have this capability so I added the option to enable this. 
On Graal, this option is enabled by default. In our case, the performance remains the same on slambench with the OpenCL backend, but there is a slowdown on PTX. Therefore, the option is disabled by default.
Also, I updated the JMH version to the latest and cleanup `PTXTornadoDevice::ensureAllocated`
Run the unit tests on both backends and the JMH benchmarks.
`tornado-test.py --verbose -J"-Dtornado.{opencl,ptx}.priority=XXX -Dtornado.compiler.bytecodeInlining=True"`
`tornado-benchmarks.py --jmh`

Add option to inline during bytecode parsing

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLLowTier.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java

This PR provides a hotfix for making kfusion running on Nvidia GPUs (OpenCL), as it is reported in issue #104. This is not a solution for why `fix-reads` break kfusion on Nvidia GPUs, but a hotfix. I have also added a `TODO` comment.
The PR introduces a new flag in the TornadoOptions class, which can be used by any user programs that need the `fix-reads` disabled. The default value is `True`. This flag is being used to deactivate fix-reads only for OpenCL, as this phase seems to work when I tested the PTX backend for `unit-tests`, `benchmarks`, `kfusion`).
```bash
$ make
$ make tests
$ make BACKEND=ptx,opencl
$ make tests # It will select the PTX by default 
```
I also run `kfusion` in both GUI and benchmarking modes. To reproduce, run:
```bash
$ …
```

Hotfix for disabling FixReads to make kfusion run on Nvidia GPUs

---

assembly/src/examples/generated/virtualDevice/virtualDeviceKernelGPU.cl
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLKind.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/LocalArrayNode.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXKind.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/LocalArrayNode.java

This PR provides a patch that refactors the `OCLKind` and `PTXKind` to be resolved from the JavaKind. This includes a new method for each backend. This refactoring fixes the inconsistency between the two backends (OpenCL, PTX) regarding the `LocalArrayNode`, as mentioned in issue #89.
As it is shown in the under-review files, the refactored code of this patch fixes the generated GPU [kernel](https://github.com/beehive-lab/TornadoVM/blob/master/assembly/src/examples/generated/virtualDevice/virtualDeviceKernelGPU.cl) that is required for the `testVirtualDeviceKernel` unit-test to use an array name `f_2` instead of `ul_2` (line 29) for the float local array.
- The patch has been tested for both backends (`OpenCL`, `PTX`) and the benchmarks, as …

[Fix] OCLKind/PTXKind inconsistency in code gen

---

assembly/src/examples/generated/add.ptx
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/PTXCodeUtil.java

A single thread was scheduled for some tasks when running the `BlurFilterTornado` benchmark with the PTX backend.
This is a temporary fix that replicates what happens on the OpenCL backend. I think the ideal solution is to decouple the domain from any of the compiler phases.
The issue is that multiple task schedules use the same entry in the code cache. This stops the `TornadoShapeAnalysis` phase from running and setting the domain in the task meta, causing a single thread to be scheduled for the kernel.
```
Task info: blur.red                                                                                      
Backend           : PTX                                                                          
Device            : GeForce GTX 1650 GPU …
```

Fix scheduling when multiple task schedules use the same Java method 

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLEventsWrapper.java

This PR fixes a memory leak caused by the way TornadoVM interacts with the OCL driver.
Events were marked as released in the runtime but calls to `clReleaseEvent` were not made when calling `device.reset()`.
For long-running processes, this caused increased memory usage. 
On the PTX backend, we perform the required driver calls. 
Running the unit tests should cover this. Between tests, we always call `device.reset()`.

Release OCL events when calling device reset 

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLCodeCache.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLHighTier.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLNodeLIRBuilder.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/IntelUnrollPragmaNode.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/XclPipelineAttribute.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/XilinxPipelineAttribute.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/XilinxPipeliningPragmaNode.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoFPGAPragmas.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLDeviceContext.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoDeviceContext.java

This PR provides enhancements for the generated code that target Xilinx FPGAs.
In particular two features are introduced:
- The ability to instantiate multiple compute units for the same kernel.
- The transparent addition of the `__attribute__((xcl_pipeline_loop(1)))`. (1 is the default initiation interval value (II) used by Xilinx HLS tools).
1. With regards to the first feature, we have seen up to 2.5x performance improvement when fitting multiple compute units on the FPGA. In particular for the DFT and 65536 input size, we managed to fit up to 12 kernels on the Xilinx KCU1500 FPGA. The problem that did not allow this flag to work was due to an inability in the `OCLCodeCache` to parse the `--nk computeDft:2` as a flag in the FPGA configuration file.
This flag is tested with SDAccel …

[FPGA] Enhancement of Xilinx OpenCL backend

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLArithmeticTool.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXArithmeticTool.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestMath.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestTornadoMathCollection.java

Ternary nodes should infer the LIR type using the three operands. LIR types for `FMA` instructions were getting the LIR with the first two values, instead of the 3 operands. This patch fixes that. 
```bash 
make tests
tornado-test.py -pk --debug -V -J"-Ds0.t0.device=0:0" --fast uk.ac.manchester.tornado.unittests.matrices.TestMatrices#testMatrixMultiplication
```

[fix] FMA LIR Type fixed for ternary nodes

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLDeviceContext.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/CompilableTask.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/PrebuiltTask.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/SchedulableTask.java

This PR includes two complementary changes to PRs #121 and #122.
1. The fix of duplication with regards to the logic of `isPlatformXilinxFPGA()`.
2. The fix with regard to the renaming of the  method  `setGridScheduler(boolean use)` with `setUseGridScheduler(boolean use)`.
All unit-tests are passing. Try:
```bash
$ make 
$ make tests
$ make BACKEND=ptx
$ make tests
```

[refactor] Misc fixes

---

assembly/src/bin/tornado-test.py
examples/src/main/java/uk/ac/manchester/tornado/examples/compute/NBody.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/ComputeTests.java

Check benchmarks are functionally correct via unittests
Github issue #415 (Internal)
Thank you for contributing to TornadoVM. This template provides checkpoints before the PR and a template to be filled
when submitting a PR on Github.
```bash
$ tornado-test.py -V --fast uk.ac.manchester.tornado.unittests.compute.ComputeTests
```
Checked also with JDK 8 JVMCI 21.1 & GraalVM 21.1 (JDK 11)

[tests] Compute-Test added as unittests

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLBlockVisitor.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompilationResultBuilder.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLNodeLIRBuilder.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLLIRStmt.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/codegen/CodeGen.java

Describe the patch. What does it enhance? What does it fix?
This PR addresses the following issues; 
1) fix closing brackets on some edge cases
2) update end loop phi variables regardless the loop runs or not
1) There are edge cases we did not cover during code gen and emitted the invalid code. 
2) If a loop never iterates and some phi variables of the loop are used after the loop, then we need to assign them outside the loop body. 
In the code below, `i_308` and `i_309` are never assigned a value when the loop does not iterate
```
i_363  =  i_195;
i_364  =  i_170;
for(;i_364 < i_111;) {
... loop body where we use `i_363` and `i_364` ....
i_308  =  i_363;
i_309  =  i_364;
}
... use `i_308` and `i_309` outside the loop...
```
To fix this, we emit the phi assignments after we close the loop …

Fix brackets issue on some extra edge cases

---

assembly/src/bin/tornado-test.py
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/plugins/PTXGraphBuilderPlugins.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/api/KernelPluginsTests.java

This PR enables the method `getGlobalThreadSize` as a compiler plugin. This method was missing from the initial implementation of the `KernelContext`. 
For both backends:
```bash
tornado-test.py --threadInfo --printKernel --fast -V uk.ac.manchester.tornado.unittests.kernelcontext.api.KernelPluginsTests
```

Register Graal Compiler Plugin for accessing the global number of threads in OpenCL/PTX

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLEvent.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLKernelScheduler.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLInstalledCode.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXEvent.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/EmptyEvent.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskSchedule.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/ProfiledAction.java

Refactor in the ProfilerAction class
* event.getExecutionTime -> event.getElapsedTime
* event.getExecutionTimeInSeconds -> getElapsedTimeInSeconds 
All tests should run
``` 
$ make tests 
```

[refactor] event.getExecutionTime -> event.getElapsedTime

---

README.md
assembly/src/docs/15_FAQ.md

This PR contains minor updates in terms of documentation. In particular, it contains the following changes:
- Update JDK 16 in the list of JDKs that TornadoVM can be installed with.
- Minor typos.
- Addition of a reference to the TornadoVM [installer](https://github.com/beehive-lab/tornadovm-installer) for Linux and Mac OSx.

[docs] Minor updates in README.md & 15_FAQ.md

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLLoweringProvider.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLLIRGenerator.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/VectorPlugins.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLAddressNode.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLGenTool.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/vector/VectorAddNode.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/vector/VectorStoreGlobalMemory.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/plugins/PTXVectorPlugins.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXAddressNode.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXGenTool.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/vector/VectorAddNode.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/vector/VectorStoreGlobalMemory.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/MarkVectorStore.java
runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoDataflowAnalysis.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/tasks/TestMultipleFunctions.java

This PR fixes vector stores to method parameters when calling the `set` method. Previously the test from `TestMultipleFunctions::testVector01` was failing with a compile time error.
The ideal graph generated before the patch is:
The ideal graph generated after the patch is:
The new node `VectorStoreGlobalMemory` performs a single `vstore` operation to global memory. 
```
__kernel void vectorTypes(__global uchar *_heap_base, ulong _frame_base, __constant uchar *_constant_region, __local uchar *_local_region, __global int *_atomics)
{
ulong ul_2, ul_0, ul_4; 
float f_10, f_9, f_8, f_7; 
float4 v4f_6, v4f_5, v4f_11, v4f_12, v4f_3, v4f_1; 
__global ulong *_frame = (__global ulong *) &_heap_base[_frame_base];
// BLOCK 0
ul_0  =  (ulong) _frame[3];
v4f_1  =  vload4(0, (__global float *) ul_0); …
```

[OCL][PTX] fix vector stores to parameters

---

tornado-annotation/pom.xml

Fixes issue https://github.com/beehive-lab/TornadoVM/issues/152.
Fixes incompatibility with Java17, not intercepted by existing tests.
https://github.com/beehive-lab/TornadoVM/issues/152.
- [X ] OpenCL
- [X ] Linux
- [X ] No
Provide instructions about how to test the new patch. 
`make test`

asm 9.2 for Java17 compatibility.

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/AbstractWorkerGrid.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/Policy.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskSchedule.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoVM_Intrinsics.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/runtime/TornadoAPIProvider.java

TaskSchedules with 13 and 14 arguments returned a `TornadoAPI` object instead of a `TaskSchedule` object. 
This PR provides a fix and it removes old imports and some changes in the API to comply with Sonar tool. 
This PR solves issue #155 
All Unittests should pass.

[fix] #155 (public) TaskSchedule return type for task13 and 14

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLLIRGenerator.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXLIRGenerator.java
drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/SPIRVLIRGenerator.java
drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/lir/SPIRVBinary.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/branching/TestConditionals.java

This PR implements the `IntegerTestMove` operation in the three backends; OpenCL, PTX, SPIR-V.
This operation performs a bitwise and operation between two operands and based on the outcome a value is assigned to a variable. In Java this is the test that was reproduced by issue #176:
```java
public static void integerTestMove(int[] output, int dimensionSize) {
for (@Parallel int i = 0; i < dimensionSize; i++) {
for (@Parallel int j = 0; j < dimensionSize; j++) {
if ((i % 2 == 0) & (j % 2 == 0)) {
output[i + j * dimensionSize] = 10;
} else {
output[i + j * dimensionSize] = -1;
}
}
}
}
```
I also added the aforementioned testcase in the TornadoVM `TestConditionals` unit-tests.
Thanks to @gigiblender and @jjfumero for their assistance in some issues related to PTX and SPIR-V. The generated …

[fix/176] Implement IntegerTestMove operation in OpenCL, PTX, SPIRV

---

assembly/src/bin/tornadoLocalInstallMaven

This PR fixes the TornadoVM version associated with the maven install script. 
Maven Local Install version updated to `0.15-dev`.
How to test?
```bash
$ tornado --mavenLocalInstall
```
Related issue: #189

[conf] Maven Local Install script fixed to 0.15-dev

---

drivers/opencl-jni/src/main/cpp/source/OCLProgram.cpp
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/CUDAVersion.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDevice.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXVersion.java
drivers/spirv-levelzero-jni/src/main/cpp/src/levelZeroContext.cpp
drivers/spirv-levelzero-jni/src/main/cpp/src/levelZeroDescriptors.cpp
drivers/spirv-levelzero-jni/src/main/cpp/src/levelZeroModule.cpp
unittests/src/main/java/uk/ac/manchester/tornado/unittests/prebuilt/PrebuiltTest.java

This PR extends/fixes the PTX header for newer GPUs with Compute Capability >= 7.5. This PR has been tested for 2060, 1050 and 3070 GPUs. 
Note that, due to an error in the Kernel Launch when using the NVIDIA GPU driver >= 510.60, some of the kernels do not work. However, this PR updates the header for the assembly PTX code for running on modern GPUs. 
Additionally, this PR fixes the JNI code of Level Zero and the SPIR-V backend., 
This PR affects to the PTX and SPIR-V backends.
```bash
$ make BACKEND=ptx
$ tornado --threadInfo --printKernel -Ds0.t0.device=0:0 -m tornado.examples/uk.ac.manchester.tornado.examples.compute.MatrixMultiplication2D
.version 7.6            ## VERSION UPDATED
.target sm_75 …
```

CUDA PTX Header Fixed

---

drivers/opencl-jni/src/main/cpp/source/OCLProgram.cpp
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLKernelScheduler.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLInstalledCode.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/CUDAVersion.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDevice.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXVersion.java
drivers/spirv-levelzero-jni/src/main/cpp/src/levelZeroContext.cpp
drivers/spirv-levelzero-jni/src/main/cpp/src/levelZeroDescriptors.cpp
drivers/spirv-levelzero-jni/src/main/cpp/src/levelZeroModule.cpp
unittests/src/main/java/uk/ac/manchester/tornado/unittests/prebuilt/PrebuiltTest.java

Thread info was disabled for single-thread OpenCL generated programs. This PR supports debug info also for single thread kernels. This is reachable from automatic reductions in the final merge step, for example. 
This fixes issue #197
This PR only affects the OpenCL Backend
```bash
$ make BACKEND=opencl
$ tornado --threadInfo -ea -Dtornado.unittests.verbose=True -Xmx6g -Dtornado.recover.bailout=False  -m  tornado.unittests/uk.ac.manchester.tornado.unittests.tools.TornadoTestRunner  uk.ac.manchester.tornado.unittests.reductions.TestReductionsFloats#testComputeAverage
```

[hotfix] OpenCL ThreadInfo option fixed for Automatic Reductions

---

drivers/ptx-jni/src/main/cpp/source/PTXStream.cpp
drivers/ptx-jni/src/main/cpp/source/ptx_utils.cpp
drivers/ptx-jni/src/main/cpp/source/ptx_utils.h
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTX.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXPlatform.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXStream.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/PTXArchitecture.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/backend/PTXBackend.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/mm/PTXKernelArgs.java
drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/SPIRVLevelZeroInstalledCode.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsFloats.java

This PR provides a fix for #195. The issue is that, from the NVIDIA Driver 510.60, the driver checks for the argument size of each parameter passed to the kernel. This was, in fact, a bug in the TornadoVM runtime. This patch provides a fix by using all buffers of the same size, and then padding when necessary. 
With this patch, TornadoVM can run many unittests, including Matrix Multiplication benchmarks. However, there are still some errors during the kernel launch only when using the TornadoVM Kernel API. The fix for this part will be provided in a separate PR. Additionally, some of the reductions produce not-correct results (only from 30XX GPUs with NVIDIA driver >= 510.60). 
This will be also patched in a separated PR. 
The TornadoVM backend for GPUs using NVIDIA Drivers <= 510.54 is …

[PTX] Fix #195: PTX Kernel Signature match with arguments size during kernel launch

---

drivers/ptx-jni/src/main/cpp/source/PTXStream.cpp
drivers/ptx-jni/src/main/cpp/source/ptx_utils.cpp
drivers/ptx-jni/src/main/cpp/source/ptx_utils.h
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTX.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXPlatform.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXStream.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/PTXArchitecture.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/asm/PTXAssemblerConstants.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/backend/PTXBackend.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/mm/PTXKernelArgs.java
drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/SPIRVLevelZeroInstalledCode.java
unittests/src/main/java/uk/ac/manchester/tornado/unittests/reductions/TestReductionsFloats.java

When running on new NVIDIA GPUs (e.g., 3070) with the latest NVIDIA Drivers (>= 510.60), TornadoVM does not generate the whole signature for the Kernel Context API. This is by design since the kernel context is always used. However, when using the new NVIDIA drivers, all kernel arguments must match in size and type with the kernel signature. 
This PR provides a fix for this scenario in which the kernel API is used. By design, we keep the first parameter as kernel context. If we have a Java parameter that represents the Kernel Context, we also add a new parameter to the PTX kernel signature using a different name.  
Related issue #195 
This PR only affects the PTX backend: 
```bash
$ make BACKEND=ptx
$ …
```

[FIX][PTX] Kernel Signature and argument list fixed when running with the Kernel Context API

---

assembly/src/bin/tornado

`tornado` script fixed for Windows 11. The problem was that the PATH was using the Linux directory separator (`/`) instead of the Windows separator (`\`). 
This change has been tested for Windows 11 using MSYS64 for the OpenCL and PTX backends. 
Issue related #179

[tooling] tornado script for Win11 fixed

---

drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDevice.java
drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLDevice.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDevice.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXGridInfo.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXModule.java
drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXScheduler.java
drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVLevelZeroDevice.java
drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVOCLDevice.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoTargetDevice.java

When running TornadoVM using the PTX backend on 30XX GPUs, the thread block was not calculated correctly. For 1D we what to maximize the occupancy but the runtime was obtaining a lower number of threads compared to th JIT compiler during the partial evaluation.
This patch provides a fix for this by using the `maxThreadBlock` instead of the max occupancy in the case of 1D kernels.
Related issue #194 
This affects the reductions and the PTX backend:
```bash
make BACKEND=ptx
tornado-test --threadInfo -V uk.ac.manchester.tornado.unittests.reductions.TestReductionsFloats
```

[Fix] PTX Thread Block for 1D Reductions

---

docs/source/installation.rst

This PR fixes the documentation about the installation with the automatic install script with GraalVM. The option for the GraalVM JDK version was not correct. 
Related issue: https://github.com/beehive-lab/TornadoVM/issues/235

[docs] Installation with GraalVM updated

---

pom.xml
scripts/installerConfig.py

When I tried the installer on Windows 11 (WSL) the maven links were broken. The maven binaries were updated recently and we need to update the URL to the latest version.  
```bash
$  ./scripts/tornadovm-installer --jdk graalvm-jdk-17 --backend opencl
```

[install] Fix the maven links

---

docs/source/installation.rst
docs/source/unsupported.rst

This PR updates the documentation, hosted in https://tornadovm.readthedocs.io/en/latest/ with the following changes:
1. Update the installation instructions for Windows 10/11 with MSys2
2. Fixed typos on the `unsupported` page. 
The new version of the documentation will be rendered automatically with this PR.

[docs] Windows 10/11 installation updated

---

.readthedocs.yaml
docs/.readthedocs.yaml

Fix for Read The Docs. Since last week, we are getting the following exception with OpenSSL:
```bash
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/tornadovm/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 280, in build_main
args.pdb)
File "/home/docs/checkouts/readthedocs.org/user_builds/tornadovm/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 219, in __init__
self.setup_extension(extension)
File "/home/docs/checkouts/readthedocs.org/user_builds/tornadovm/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 398, in setup_extension
self.registry.load_extension(self, extname)
File "/home/docs/checkouts/readthedocs.org/user_builds/tornadovm/envs/latest/lib/python3.7/site-packages/sphinx/regist …
```

[docs] YAML config file for ReadTheDocs added

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLPlatform.java

Change applied on behalf of @iotamudelta for the Mesa OpenCL GPU Driver.
How to test it?
> Obtain recent Mesa with rusticl module enabled, then set RUSTICL_ENABLE=radeonsi and RUSTICL_FEATURES=fp64, and install TornadoVM with OpenCL backend. To test: tornado-benchmarks.py.
PR related: #270 

[runtime] Support for Mesa's rusticl

---

tornado-assembly/src/bin/tornado

From GraalVM 23.0.1 with JDK 20, there is a header of 16 bytes when querying the JVMCI API:
`MetaAccessProvider.getArrayBaseOffset`
The TornadoVM JIT compiler reads the value from this interface to setup the bytes for the object headers on the GPU (or accelerator).
However, OpenJDK sets the value to 24 bytes, as any previous version of JDK. The issue is that, in OpenJDK, compressed oops and compressed class pointers independent from this commit:
https://github.com/openjdk/jdk/commit/382e5dc334502d9147977d50a210ed503ca9fe3e#diff-3dff3621045b158b101e55710fa74455c006ab1ec963111ebef657ff3b7abeaaR73
And when the JVMCI is enabled compressed it also enables both `CompressedOops` and `CompressedClassPointers`, as here:
https://github.com/openjdk/jdk/commit/382e5dc334502d9147977d50a210ed503ca9fe3e# …

[compiler][flag] Fix for GraalJIT 23 and object headers.

---

tornado-assembly/src/bin/tornado-benchmarks.py

The --profiler flag didn't work, since when enabled by the user, the flag was added to JVM options, however, it should be placed in front of the tornado command and not JVM options.
Hence, the options variable is updated to two separate variables: jvm_options and tornado_options, so every option will be placed in its right place.
JVM didn't recognize the --enableProfiler flag and showed the following error:
```
tornado --jvm="-Xms24G -Xmx24G -server -Dtornado.recover.bailout=False  -Dtornado.benchmarks.skipserial=True  --enableProfiler silent "  -m tornado.benchmarks/uk.ac.manchester.tornado.benchmarks.BenchmarkRunner --p
arams="saxpy"
Unrecognized option: --enableProfiler
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
You …

[fix] fix --profiler flag in tornado-benchmarks.py script

---

bin/installer_config.py

Fixed the download link for GraalVM21 in the install scripts, `./bin/installer_config.py`
The original download link is redirected to [the release page](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-21.0.1). This is an HTML resource rather than gzip, and will throw an exception when the script tries to decompress it
```
Checking dependency: graalvm-community-jdk-21.0.1_macos-aarch64_bin.tar.gz
Traceback (most recent call last):
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tarfile.py", line 1682, in gzopen
t = cls.taropen(name, mode, fileobj, **kwargs)
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/tarfile.py", line 1659, in taropen
return cls(name, mode, …
```

Fix GraalVM JDK21 download urls in installer_config.py

---

tornado-assembly/src/bin/tornado-benchmarks.py

This PR fixes the old classpath of TornadoVM when running the benchmarks with the JMH option. 
```bash
$ make
$ tornado-benchmarks.py --jmh
```

[fix] benchmark classpath with JMH option

---

bin/tornadovm-installer

This PR fixes the install script. There was an error of undeclared variable when the `polyglot` mode was not used. 
```bash
./bin/tornadovm-installer --jdk jdk21 --backend=opencl
```

[fix] Installer with no polyglot configuration

---

docs/source/programming.rst

I reformatted the `KernelContext` table to avoid confusing whitespaces. I also fixed typos in the same file.
I built the docs locally to make sure it looks fine now:
The `KernelContext` table in `programming.rst` had linebreaks in words, leading to spaces on the [website](https://tornadovm.readthedocs.io/en/latest/programming.html#kernelcontext-features):
This change can be tested by building the docs locally using `make html` and looking at the generated `programming.html` file.

Reformat KernelContext table

---

tornado-assembly/src/bin/aws_post_processing.sh

Currently, tornado gets a configuration file for running codes on fpga.
On AWS instances, the configuration needs some metadata about S3 bucket
and related folders to upload files on S3, however, aws_post_processing.sh
is not using these metadata properly. This fix uses the defined variables
to run create_vitis_afi.sh
If user has different bucket and folder names in their S3, tornado 
will fail to upload generated files to S3. So, this will prevent create_vitis_afi.sh 
script to generate AFI image for FPGA on AWS and the image will not be 
available for tornadovm to run on the FPGA device.  Also, any additional
white space after the equal sign and the value, will be propagated to the
create_vitis_afi.sh and …

Fix aws s3 configuration usage in aws_post_processing.sh

---

docs/source/programming.rst
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/BatchConfiguration.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/batches/TestBatches.java

TornadoVM currently requires all inputs to have the same size when using batching.
However, the BatchConfiguration only checked that for java arrays before. That seems unintended.
The patch moves the check until after the loop to also cover TornadoVM array types.
I ran the tests locally and saw some failures, but from inspecting them, none of the failing tests uses batching, so the failures are likely unrelated.
From reading the code, I noticed that the check only covers Java arrays. I wrote a test that ensures that mismatching sizes are discovered early instead of crashing the JVM.
Run the added tests (potentially with the changes to BatchConfiguration reverted).

Move input sizes check to also check for tornado arrays

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLBlockVisitor.java

This PR provides a fix for a corner case that was showcased in the Discussion thread #292. 
The issue identified was that, for a method that does not have the `@Parallel` annotation in the indexing of the for-loops, and which has nested if-statements, an extra close curly bracket was generated incorrectly. With this PR, the code generation is fixed to only generate a close curly bracket in a nested if-statement block if it is not a merge block. 

[fix] Fix codegen to not generate wrong close curly bracket 

---

Makefile
bin/compile
bin/softwareDevDependencies.txt
bin/tornadoDepModules.txt

This PR improves the installation process for all backends and includes a cache compilation of all SPIR-V package/module dependencies. 
We do not need to pull and rebuild all SPIR-V dependencies with every TornadoVM build. 
We can force to rebuild the dependencies by running:
```bash
make rebuild-deps-jdk21 BACKEND=spirv
```
Otherwise, if the depdenceis are not present, it will only download and build the first time.
This speeds up the TornadoVM build process for SPIR-V. 
Related issue #299 
```bash
$ rm -Rf levelzero-jni/ level-zero/ spirv-beehive-toolkit/
```
To force rebuild all dependencies:
```bash
$ make rebuild-deps-jdk21 BACKEND=spirv …
```

[fix][install] Python module deps fixed. SPIR-V installer improved

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/GridScheduler.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraph.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoTaskGraphInterface.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/PrebuiltTaskPackage.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/TaskPackage.java
tornado-assembly/src/bin/tornado-test
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/analyzer/ReduceCodeAnalysis.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/analyzer/TaskUtils.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/compiler/TornadoCompilerIdentifier.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/PrebuiltTask.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/grid/TestGridScheduler.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/api/Grids.java

Grid Schedulers contain the name of an existing task graph and a task name. However, it could be possible that, due to a programmer's error, the grid name does not match with any existing tasks within the assigned task-graph. This PR adds this check and it refactors the PrebuilTask API to use the same style as the Compilable Task API.
```bash
$ make 
$ tornado-test -V --threadInfo --printKernel uk.ac.manchester.tornado.unittests.kernelcontext.api.Grids
```
Pass also all unit-tests
```bash
$ make tests
```

[fix] Runtime Name Check for Grid Schedulers

---

tornado-assembly/src/etc/checkstyle.xml

Using String Templates caused checkstyle to fail due to unsupported rules. 
There is an open PR, so it is going to be officially supported soon. https://github.com/checkstyle/checkstyle/issues/13830#issuecomment-1892787426
However, they provided the following temporary workaround to suppress errors regarding String Templates  
https://github.com/checkstyle/checkstyle/issues/12542#issuecomment-1362261537.
```bash
```

[checkstyle] Add exception handling to checkstyle configuration to support STR templates

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/ReduceTaskGraph.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java

Related to issue #306.
Cleanup on the `TornadoTaskGraph` class to adopt string templates and improve readability and code maintenance when  
string manipulation is used.
```bash
make 
make tests
```

[#306] Impove code readibility in `TornadoTaskGraph` by adapting String Templates

---

tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVPrimitiveTypes.java

This PR fixes the warning for SPIR-V Kernels generating vector-16 instructions (e.g., Float16).
The issue is that the `spirv-val` was emitting an error due to a missing SPIR-V capability in the generated SPIR-V kernels. 
This PR adds the capability when it is required. 
This PR only affects the SPIR-V backend,
```bash
$ tornado-test --printKernel --debug -V uk.ac.manchester.tornado.unittests.vectortypes.TestFloats#testSimpleDotProductFloat16
.... 
[SPIRV-Runtime] SPIRV Registering VM Intrinsics Plugins - pending
SPIRV-File : /tmp/tornadoVM-spirv/11047078642496-s0.t0dotMethodFloat16.spv     <<< Kernel File
[SPIRV-Runtime] Set SPIR-V entry point: dotMethodFloat16
$ spirv-val …
```

[spirv][fix] emit Vector16 Capability for 16-width vectors

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/math/TornadoMath.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/asm/OCLAssembler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLMathPlugins.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLBuiltinTool.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFPUnaryIntrinsicNode.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/asm/PTXAssembler.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/asm/PTXAssemblerConstants.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/plugins/PTXMathPlugins.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXBuiltinTool.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXFPUnaryIntrinsicNode.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/plugins/SPIRVMathPlugins.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/nodes/SPIRVFPUnaryIntrinsicNode.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestMath.java

This PR adds support for the `Math.ceil` and `TornadoMath.ceil` functions for all the backends. 
Test for each of the backends
```bash
$ make BACKEND=opencl
$ tornado-test --printKernel -V --fast uk.ac.manchester.tornado.unittests.math.TestMath#testMathCeil
$ tornado-test --printKernel -V --fast uk.ac.manchester.tornado.unittests.math.TestMath#testMathCeil
$ make BACKEND=ptx
$ tornado-test --printKernel -V --fast uk.ac.manchester.tornado.unittests.math.TestMath#testMathCeil
```

[math] ceil function added 

---

bin/compile
tornado-drivers/spirv/pom.xml

This PR updates the dependency to the Beehive SPIR-V Toolkit for the SPIR-V Code gen.
This version includes the support for the Half vector types.
```bash
$ make tests 
```

[SPIRV] Beehive Toolkit version updated

---

pom.xml

This PR fixes the build for the graal-jdk21 profile.
After refactoring the driver and runtime packages, the new exports were missing from the graal-jdk21 profile.
```bash
make graal-jdk-21
```

Fix for graal-jdk21 profile in pom.xml

---

tornado-assembly/src/bin/tornado-test

This PR adds the FP16 for the OpenCL tests in the white list. The reason is that, for some devices, even though the half types are not supported, it is possible to perform FP16 computations. Thus, the TornadoVM runtime cannot throw an exception just by looking at the OpenCL properties of the device. Rather, it continues the execution of the kernel and the driver will launch an error code is the kernel is not supported. 
This does not mean that the kernel is not correct. For this reason, we add these FP16 to the white list of unit-tests. 
This PR only affects the OpenCL backend. 
```bash
make 
tornado -ea  --jvm "-Xmx6g -Dtornado.recover.bailout=False -Dtornado.unittests.verbose=True "  -m …
```

[tests] half-type (fp16) tests added in the whitelist

---

README.md
docs/source/CHANGELOG.rst
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

https://github.com/beehive-lab/TornadoVM/pull/305: Under-demand data transfer for custom data ranges. 
https://github.com/beehive-lab/TornadoVM/pull/313: Initial support for Half-Precision (FP16) data types. 
https://github.com/beehive-lab/TornadoVM/pull/315: Math `Ceil` function added 
https://github.com/beehive-lab/TornadoVM/pull/311: Enable Multi-Task Multiple Device (MTMD) model from the ``TornadoExecutionPlan`` API: 
https://github.com/beehive-lab/TornadoVM/pull/294: Separation of the OpenCL Headers from the code base.
https://github.com/beehive-lab/TornadoVM/pull/297: Separation of the LevelZero JNI API in a separate repository.
https://github.com/beehive-lab/TornadoVM/pull/301: Temurin configuration supported
https://github.com/beehive-lab/TornadoVM/pull/304: Refactor of the common …

[release] TornadoVM v1.0.1

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLInstalledCode.java

This PR fixes the duplicate printing of thread information. When both the flags for debugging (`--debug`) and thread info (`--threadInfo`) were enabled, the thread information was printed twice. In this PR, the thread information is printed only if the debug flag is not also enabled. 

Fix duplicate printing of thread info when debug is enabled

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/collections/VectorFloat4.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/images/ImageByte3.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/images/ImageByte4.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/images/ImageFloat.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/images/ImageFloat3.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/images/ImageFloat4.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/images/ImageFloat8.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix2DDouble.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix2DFloat.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix2DFloat4.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix2DInt.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix3DFloat.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix4x4Float.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/utils/StorageFormats.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/volumes/VolumeShort2.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLVectorPlugins.java
tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/compute/MatrixVector.java
tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/vectors/DFTVector.java
tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/vectors/MatrixVector.java
tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/vectors/VectorAddTest.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/ComputeTests.java

This PR fixes memory accesses (get/set)  for the `Matrix2DFloat4` type.
The problem was the the indexes were not correctly computed. In addition, no unit-tests was present to check this. 
This PR solves the issue and adds a test for checking the memory layout and the memory accesses of this type. 
```bash
$ make 
$ make tests   ## pass all unit-tests
$ tornado-test --threadInfo --jvm="-Dgraph.mv.device=0:0" --printKernel -V --fast uk.ac.manchester.tornado.unittests.compute.ComputeTests#matrixVectorFloat4
```

[fix] MatrixVectorFloat4 set/get accesses fixed

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java

This PR fixes the dynamic reconfiguration to select the correct device depending on the input policies. 
The issue was that the timers were not correctly calculated, and it includes the whole performance evaluation in the case of the performance policy. This PR solves this issue and it refactors the sequential and parallel strategies. 
This PR has been tested with the OpenCL backend
```bash
$ make
$ make tests
```

[fix] Dynamic reconfiguration policies

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraph.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoTaskGraphInterface.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/BatchConfiguration.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoVMBytecodeBuilder.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoVMGraphCompiler.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/batches/TestBatches.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/memoryplan/TestMemoryLimit.java

This fixes and adds support for batch processing when having a `TaskGraph` with multiple tasks. 
Besides, it removes old/unreachable methods that are not needed anymore. 
However, this PR still has the issue of incorrect results when the task-graph does not perform a copy-in. 
I added two more unit-tests, one with copy in and the other without. It seems that without copy-in, the batch processing works (compiler and internals of the runtime), but the results are not correct. 
For task-graphs with copy-in/out (which was the original intended use), multiple tasks in a taskgraph with batch processing now works. 
We can go ahead this is partial fix, and add a new extension on top of this to process also for only outputs. 
The issue was that, when having multiple tasks in a task-graph, the …

Batch Processing with Multiple tasks in a task-graph

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/profiler/TornadoProfiler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/profiler/EmptyProfiler.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/profiler/TimeProfiler.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/profiler/TestProfiler.java

It should be possible to enable the profiler after the TornadoVM Execution Plans runs the first iteration. There was an issue with the profiler that was preventing the profiler from being registered if it was not enabled in the first iteration. This commit fixes and enables the profiler at any point during runtime via the execution plan.
Example:
```java
TornadoExecutionPlan executionPlan = new TornadoExecutionPlan(taskGraph.snapshot());
// Runs without the profiler
executionPlan.execute();
// enable the profiler
TornadoExecutionResult executionResult = executionPlan.withProfiler(ProfilerMode.SILENT)
.execute();
// Query timers from the profiler
executionResult.getProfilerResult().getDeviceKernelTime();
```
If it …

[feat] Dynanically enable the profiler after the first execution

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/ImmutableTaskGraph.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraph.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoTaskGraphInterface.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/memory/TaskMetaDataInterface.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLCodeCache.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContextInterface.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/tests/TestOpenCLTornadoCompiler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLDeviceContext.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXCodeCache.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/tests/TestPTXTornadoCompiler.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVLevelZeroCodeCache.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/tests/TestSPIRVTornadoCompiler.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/RuntimeUtilities.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/ReduceTaskGraph.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/ScheduleMetaData.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/TaskMetaData.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/foundation/TestIntegers.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/profiler/TestProfiler.java

This PR enables two more methods in the `TornadoExecutionPlan` API to debug the kernels and the code dispatcher (number of threads and device in which each task in an immutable task-graph will be executed). 
This PR introduces the following methods in the task-graph:
```java
TornadoExecutionPlan executionPlan = new TornadoExecutionPlan(immutableTaskGraph);
executionPlan
.withThreadInfo()  // new method to print the thread deployment - same action as --threadInfo from the command line
.withPrintKernel() // new method to dump the generated kernel. Same action as the --printKernel from the command line 
.execute();
```
Apart from the
```bash
$ make 
$ tornado-test -V …
```

New calls to profile the Execution Plan: withThreadInfo and withPrintKernel 

---

README.md
docs/source/CHANGELOG.rst
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

Improvements
============
- #323 : Set Accelerator Memory Limit per Execution Plan at the API level
- #328 : Javadoc API to run with concurrent devices and memory limits
- #340 : New API calls to enable ``threadInfo`` and ``printKernel`` from the Execution Plan API.
- #334 : Dynamically enable/disable profiler after first run
Compatibility
============
- #337 : Initial support for Graal and JDK 21.0.2
Bug Fixes
============
- #322 : Fix duplicate thread-info debug message when the debug option is also enabled.
- #325 : Set/Get accesses for the ``MatrixVectorFloat4`` type fixed
- #326 : Fix installation script for running with Python >= 3.12
- #327 : Fix Memory Limits for all supported Panama off-heap types.
- #329 : Fix timers for the dynamic reconfiguration policies
- #330 : Fix the …

[release] TornadoVM 1.0.2

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/memory/TaskMetaDataInterface.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/SPIRVLevelZeroInstalledCode.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/analyzer/TaskUtils.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/TaskMetaData.java

This PR solves the problem of getting the wrong local work group sizes when the device is changed from the CPU using the OpenCL backend to the GPU using the SPIR-V backend. 
The problem was that, in the SPIR-V backend, once the number of blocks is computed, is then stored in the `TaskMetaData` object. However, while the global work size for the same task will not change, there is no guarantee that the local work group size is the same. This patch solves the issue by resetting the local work size only when the device is updated. 
The use case for this is the task-migration in Client/Server setup:
https://github.com/jjfumero/tornadovm-examples?tab=readme-ov-file#live- …

[fix][spirv] Reset LocalWorkSize when the device is changed

---

tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/compute/BlackAndWhiteTransform.java

Minor improvement in the Black And White filter example with TornadoVM.
```bash
$ tornado --jvm="-Drun::parallel=True" -m tornado.examples/uk.ac.manchester.tornado.examples.compute.BlackAndWhiteTransform
```

[examples] bnw example improved

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/enums/DataTypeSize.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/memoryplan/TestMemoryLimit.java

This PR extends the support introduced in #323.
Now, memory limit checks takes into account fields along with arrays and TornadoNative types.
```bash
make jdk21  BACKEND=opencl
tornado-test -V uk.ac.manchester.tornado.unittests.memoryplan.TestMemoryLimit
``` 

Refactor memory limit checks to take into account primitve type wrappers  when using the `withMemoryLimit` API

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/exceptions/TornadoDeviceNotFound.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/exceptions/TornadoDriverNotFound.java
tornado-assembly/src/bin/tornado-test
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDriver.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDriver.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVDriver.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoCoreRuntime.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestDevices.java

This PR improves the driver and device handling in TornadoVM from the user side. When a Driver or Device is requested using the corresponding indexes, the TornadoVM runtime will throw an exception if the driver/device is not present.
The main issue was that the exception thrown was generic, and it did not contain information about the problem.  
This PR has been tested on OSx with the OpenCL backend. However, it should work for any of the backends. 
```bash
$ make
$ tornado-test -V uk.ac.manchester.tornado.unittests.api.TestDevices
$ make tests
```

[API] Launch an exception when Driver/Devices indexes are not found

---

tornado-benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/ComputeKernels.java
tornado-benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/dft/DFTTornado.java

This PR replaces the DFT application benchmark from using FP64 to FP32. 
In some systems, such as Apple M1/M2, there are no FP64 support. However, TornadoVM can still process the application by processing with less precision.
```bash
$ make
$ tornado -m tornado.benchmarks/uk.ac.manchester.tornado.benchmarks.BenchmarkRunner dft 15 8192
```

DFT benchmark in FP32

---

tornado-api/src/main/java/module-info.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/IntArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/utils/TornadoAPIUtils.java
tornado-assembly/src/bin/tornado-test
tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/code/CodeUtil.java
tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/mm/PrimitiveSerialiser.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLInstalledCode.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/backend/OCLBackend.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoTaskSpecialisation.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLObjectWrapper.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/PTXCodeUtil.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/backend/PTXBackend.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/phases/TornadoTaskSpecialisation.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/phases/TornadoTaskSpecialization.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoCoreRuntime.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/analyzer/TaskUtils.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/RuntimeUtilities.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestInitDataTypes.java

Fixes the tests in the `TestInitDataTypes` class
Run the tests, including the `TestInitDataTypes`
```tornado-test -V uk.ac.manchester.tornado.unittests.api.TestInitDataTypes```

Fix the tests in TestInitDataTypes

---

pom.xml
tornado-assembly/src/bin/tornado-test
tornado-unittests/src/main/java/module-info.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/vector/api/TestVectorAPI.java

This is a follow up PR to #350 .
The PR adds unit-tests to check the connection between TornadoVM native types (invoking the getSegment) and Java Vector API.
It adds the following tests:
```
test64BitVector   ->  Species[float, 2, S_64_BIT]
test128BitVector  ->  Species[float, 4, S_128_BIT]
test256BitVector  ->  Species[float, 8, S_256_BIT]
test512BitVector  ->  Species[float, 16, S_512_BIT]
```
```bash 
make 
tornado-test -V uk.ac.manchester.tornado.unittests.vector.api.TestVectorAPI
```

Test VectorAPI with TornadoNative types through Memory Segments for 64 to 512Bit vector

---

tornado-drivers/spirv/pom.xml

This PR updates the dependency for the Beehive SPIR-V Toolkit to the latest version in preparation for the integration of the Windows Native Installer. 
n/ a.
This PR only affects the SPIR-V backend.
To test properly, I removed the m2/repo directory as well as the local directory with the dependencies
```bash
rm -Rf ~/.m2/repository/*
rm -Rf beehive-spirv-toolkit/ levelzero-jni/
make tests
```

[spirv] Update the SPIR-V Toolkit dep. to 0.0.4

---

tornado-drivers/spirv/pom.xml

This PR updates the dependency with our external JNI library for Level Zero. The 0.1.3 version brings Windows 10/11 installation and can be used for the TornadoVM windows native installation. 
n/a.
This PR only affects the SPIR-V/LevelZero  backend
```bash
$ rm -Rf levelzero-jni/
$ make tests 
```

[update] LevelZero-JNI dependency updated

---

bin/compile
bin/tornadovm-installer.cmd

This PR fixes the links to obtain the dependencies for SPIR-V Toolkit and Level Zero JNI
The problem was that there were some left-over dependencies to check the Native Windows installation. This PR fixes those with the official repos. 
```bash
make BACKEND=opencl,spirv,ptx
make tests
```

[fix] Links for LevelZero JNI and Beehive SPIR-V Toolkit fixed

---

README.md
docs/source/CHANGELOG.rst
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

TornadoVM 1.0.3 Release with the following changes:
- #344  : Support for Multi-threaded Execution Plans.
- #347  : Enhanced examples.
- #350  : Obtain internal memory segment for the Tornado Native Arrays without the object header.
- #357  : API extensions to query and apply filters to backends and devices from the ``TornadoExecutionPlan``.
- #359  : Support Factory Methods for FFI-based array collections to be used/composed in TornadoVM Task-Graphs.
- #351 : Compatibility of TornadoVM Native Arrays with the Java Vector API.
- #352 : Refactor memory limit to take into account primitive types and wrappers.
- #354 : Add DFT-sample benchmark in FP32.
- #356 : Initial support for Windows 11 using Visual Studio Development tools.
- #361 : Compatibility with the SPIR-V toolkit v0.0.4.
- #366 : …

[release] TornadoVM 1.0.3

---

docs/source/programming.rst
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/ByteArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/CharArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/DoubleArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/FloatArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/HalfFloatArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/IntArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/LongArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/ShortArray.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestConcat.java

This pull request introduces a new method concat to multiple instances of TornadoNativeArray types into a single array. This aims at providing a straightforward and efficient way to merge several  arrays  by using Memory Segment copies and without the overhead of manual array copying.
Example usage:
```java
IntArray a = new IntArray(numElements);
IntArray b = new IntArray(numElements);
IntArray e = new IntArray(numElements);
a.init(100);
b.init(5);
e.init(12);
IntArray c = IntArray.concat(a, b, e);
```
Example size output;
```bash
Array a size: 256
Array b size: 256
Array e size: 256
---------------------------------
Concat Array c size: 768
---------------------------------
```
If it is applicable, check your …

Implement Multi-Array Concatenation using Memory Segment Copy

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLXPUBuffer.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/mm/PTXObjectWrapper.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/mm/SPIRVObjectWrapper.java

This PR handles the cases where a class field is an instance of a `HalfFloatArray`. This case was highlighted by the new Tensor implementation (PR #369). The patch is applied for all three backends. 
Run `tornado-test -V uk.ac.manchester.tornado.unittests.tensors.TestTensorTypes`

Handle cases where the class field is a half float array

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/ByteArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/CharArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/DoubleArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/FloatArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/HalfFloatArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/IntArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/LongArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/ShortArray.java

This pull request introduces a new constructor to `TornadoNativeTypes`, enabling the creation of a single instance by concatenating the contents of multiple array instances. 
- [] SPIRV
The functioality is already tests with the: 
```bash 
tornado-test -V --fast uk.ac.manchester.tornado.unittests.api.TestConcat
```

Add constructors for concatinating multiple arrays of TornadoNativeType instances

---

tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/mm/PTXMemorySegmentWrapper.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/batches/TestBatches.java

This PR provides support for lazy copy-out in batch processing. The fix is related to the issue #333.   
When the mode of the copy-out was set to `UNDER_DEMAND` on a `TaskGraph` that uses batches, the `transferToHost` copied only the first batch of the output data. In this PR, the stream-out is invoked with the appropriate offsets for each batch, writing all the data to the host buffer. 
Run the following unittests:
`tornado-test -V --fast uk.ac.manchester.tornado.unittests.batches.TestBatches#test100MBSmallLazy`
`tornado-test -V --fast uk.ac.manchester.tornado.unittests.batches.TestBatches#test100MBLazy`
`tornado-test -V --fast …

Support lazy copy-out for batch processing

---

docs/source/programming.rst
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/ByteArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/CharArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/DoubleArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/FloatArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/HalfFloatArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/IntArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/LongArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/ShortArray.java
tornado-assembly/src/bin/tornado-test
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestSlice.java

This PR adds support for the TornadoNativeArray types to create arrays from segment slice of an array.
```bash
tornado-test -V --fast uk.ac.manchester.tornado.unittests.api.TestSlice
```

Add support to create TornadoNativeArrays from a TornadoNativeArray slice 

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/memory/ObjectState.java
tornado-assembly/src/bin/tornado-test
tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/TornadoBufferProvider.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OpenCL.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLArrayWrapper.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLMemorySegmentWrapper.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLVectorWrapper.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLXPUBuffer.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/tests/TestOpenCLJITCompiler.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTX.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/mm/PTXArrayWrapper.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/mm/PTXMemorySegmentWrapper.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/mm/PTXObjectWrapper.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/mm/PTXVectorWrapper.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/tests/TestPTXJITCompiler.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVLevelZeroContext.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/mm/SPIRVArrayWrapper.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/mm/SPIRVMemorySegmentWrapper.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/mm/SPIRVObjectWrapper.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/mm/SPIRVVectorWrapper.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/tests/TestSPIRVJITCompiler.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/tests/TestVM.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/DataObjectState.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/LocalObjectState.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/multithreaded/TestMultiThreadedExecutionPlans.java

This PR fixes the multi-threaded deallocation marker within the TornadoVM runtime. This PR also fixes the code in the GAIA project. 
The issue was that we need to guarantee that the deallocator marker is executed in sychronized mode, and guarantee that the `unused` buffer item in the list was not `null`.  It can be `null` if it references the same host memory object (e.g., the same Panama-based array). 
```bash
$ make 
$ tornado-test -V --fast uk.ac.manchester.tornado.unittests.multithreaded.TestMultiThreadedExecutionPlans
```

Fix for the free memory marker of TornadoVM when running multi-threaded execution plans

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/HalfFloatArray.java

Minor fix regarding a java doc description that has:
- a parameter that is not valid, and 
- a space in the method before the first argument.
```bash
```

Check style fixed

---

tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/tensors/TestTensorTypes.java

This PR swaps the actual and expected values from the Tensor unittests. 
The signature from JUnit:
```
public static void assertEquals(float expected, float actual, float delta) 
```
But this test set the expected as actual value. 
n/a.
```bash
tornado-test -V --fast --threadInfo --debug uk.ac.manchester.tornado.unittests.tensors.TestTensorTypes
```

[fix] actual and expected values swap

---

bin/tornadovm-installer

Fix for using TornadoVM with another provided JDK
See related issue #391 
Assuming there is another JDK installed (e.g., by using `sdkman`) use the following command:
```bash
$ ./bin/tornadovm-installer --backend opencl --javaHome /home/juan/.sdkman/candidates/java/current
```

[installer][fix] Fix for using TornadoVM with another provided JDK

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/ImmutableTaskGraph.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoDeviceContext.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/TornadoDevice.java
tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/TornadoBufferProvider.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContextInterface.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLEventPool.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/OCLInstalledCode.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/backend/OCLBackend.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLDeviceContext.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVBackend.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVDeviceContext.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/matrices/MatrixAddition2D.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/JVMMapping.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestIO.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/common/TornadoTestBase.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/fails/TestFails.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/profiler/TestProfiler.java

This PR fixes the issue of sharing the `eventPool` associated to a backend-context within the TornadoVM runtime. 
This PR also updates one of the methods to reset all internal state associated to one backend. 
```diff
- driver.getDefaultDevice().reset();
+ driver.getDefaultDevice().clean();
```
This resets the code cache and all events associated to a command queue. This method can be also reached from the TornadoExecutionPlan:
```java
executionPlan.resetDevice();
```
When running Tornado execution plans from many different Java threads, there was the possibility of accessing an internal data structure from many threads. This internal data structure holds the pointers to the associated low-level events in a list. However, this list is maintained by the `<Backend>DeviceContext`, which must …

Fix for Device Events (OpenCL and SPIR-V events) when running Multi-threaded Execution plans

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/memory/DeviceBufferState.java
tornado-assembly/src/bin/tornado-test
tornado-drivers/opencl-jni/src/main/cpp/CMakeLists.txt
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OpenCL.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/tests/TestOpenCLJITCompiler.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTX.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/tests/TestPTXJITCompiler.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/tests/TestSPIRVJITCompiler.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/XPUDeviceBufferState.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/DataObjectState.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/multithreaded/TestMultiThreadedExecutionPlans.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/tensors/TestTensorAPIWithOnnx.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/tensors/TestTensorTypes.java

This PR fixes an issue sharing the `dataObjectState` with multiple Java threads. 
The problem was that this state must be per thread (private), otherwise, when a buffer is allocated/removed, the device buffer taken might end-up being deallocated twice, thus, provoking a seg-fault from the driver side. This PR solves this issue. 
Disclaimer: I can run without errors using the OpenCL and SPIR-V backends. However, when running with the PTX backend, I still get random errors in the JNI side, mostly related to events. But IMO, this is not related to this fix.
```bash
$ make 
$ make tests 
$ tornado-test --jvm="-Dtornado.device.memory=4GB" --debug -V --fast …
```

New Iteration for achieving Multi-Threaded Execution Plans

---

README.md
bin/tornadovm-installer
docs/source/CHANGELOG.rst
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

- [#369](https://github.com/beehive-lab/TornadoVM/pull/369): Introduction of Tensor types in TornadoVM API and interoperability with ONNX Runtime.
- [#370](https://github.com/beehive-lab/TornadoVM/pull/370): Array concatenation operation for TornadoVM native arrays.
- [#371](https://github.com/beehive-lab/TornadoVM/pull/371): TornadoVM installer script ported for Windows 10/11.
- [#372](https://github.com/beehive-lab/TornadoVM/pull/372): Add support for ``HalfFloat`` (``Float16``) in vector types.
- [#374](https://github.com/beehive-lab/TornadoVM/pull/374): Support for TornadoVM array concatenations from the constructor-level.
- [#375](https://github.com/beehive-lab/TornadoVM/pull/375): Support for TornadoVM native arrays using slices from the Panama API.
- …

[release] TornadoVM v1.0.4

---

README.md

Example in the README page updated.
n/ a.
Not applicable
Not applicable
Not applicable

[docs] Example in the front README page updated

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/memory/TaskMetaDataInterface.java
tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/utils/CompilerUtil.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompiler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoParallelScheduler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXCompiler.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/phases/TornadoParallelScheduler.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/SPIRVCompiler.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/phases/TornadoParallelScheduler.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/JVMMapping.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/Tornado.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoSchedulingStrategy.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/sketcher/TornadoApiReplacement.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/sketcher/TornadoAutoParalleliser.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoGraphBuilder.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java

Cleanup and refactor of the code for analysis of parallel loops and loop interchange. This PR also eliminates old code no longer needed. Loop reordering option renamed to `loop.interchange`. This option is enabled by default. 
n/ a.
```bash
make
make tests
```

[Refactor] Cleanup and refactor of the code for analysis of parallel loops and loop interchange

---

bin/tornadovm-installer
docs/source/installation.rst

This PR adds automatic installation of all required python modules to compile and run TornadoVM. 
n/ a.
Invoke the installer:
```bash
> .\bin\windowsMicrosoftStudioTools2022.cmd
> python -m venv .venv
> .venv\Scripts\activate.bat
> python .\bin\tornadovm-installer --jdk jdk21 --backend=opencl
```

[installer] install python dependent python modules with pip

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/ByteArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/IntArray.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractMetaData.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestBuildFromByteBuffers.java

There were some issues regarding the checkstyle of code base. 
```bash
...
[INFO] There are 3 errors reported by Checkstyle 9.3 with tornado-assembly/src/etc/checkstyle.xml ruleset.
[ERROR] src/main/java/uk/ac/manchester/tornado/api/types/arrays/IntArray.java:[24,8] (imports) UnusedImports: Unused import - java.lang.foreign.ValueLayout.
[ERROR] src/main/java/uk/ac/manchester/tornado/api/types/arrays/IntArray.java:[139] (regexp) RegexpSinglelineJava: Illegal trailing whitespace(s) at the end of the line.
[ERROR] src/main/java/uk/ac/manchester/tornado/api/types/arrays/ByteArray.java:[26,8] (imports) UnusedImports: Unused import - java.nio.FloatBuffer.
```
This PR fixes them.
If it is applicable, …

[chore] Checkstyle errors fixed

---

tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/fields/TestFields.java

This PR updates the `TestFields` unittest to use the latest Panama types that TornadoVM provides. 
Run `tornado-test -V uk.ac.manchester.tornado.unittests.fields.TestFields`

Refactor TestFields unittest to use Panama data types

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLScheduler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/enums/OCLDeviceType.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLTornadoDevice.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/Tornado.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java

This PR provides an enhancement for the thread-block scheduler when running on the CPUs. The default thread scheduler assigns a CPU thread per CPU core. This might not be the best strategy and it really depends on the OpenCL runtime/driver implementation. This patch, provides a switch for CPU-Block versus fine-grained scheduler, and it sets, by default, the CPU thread scheduler to the fine-grained. 
The main problem is performance. For example, when running on the CPU using the PoCL OpenCL implementation, the CPU implementation takes, in average ~46 seconds to complete, while the Intel oneAPI takes ~5 seconds. 
If, instead of the block-scheduler for CPU, we use the "iteration" of the fine-grained scheduler, TornadoVM with PoCL runs in ~2.9-3.2 (s) per iteration. 
Here's a trace with PoCL …

[OCL] CPU Block Scheduler disabled by default and option to switch between thread schedulers

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/TornadoSketchTierContext.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graal/phases/sketcher/TornadoApiReplacement.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/sketcher/TornadoSketcher.java

This PR disables the loop interchange when the code is specialised for the CPU multi-core. 
When running on Intel CPU i9-10885H and OpenCL CPU Runtime `2024.17.3.0.08_160000` from oneAPI, the time that takes to compute the [Blur Filter](https://github.com/jjfumero/tornadovm-examples/blob/master/src/main/java/io/github/jjfumero/BlurFilter.java) goes from ~57 seconds in the first iteration down to ~7 seconds (speedup of 7.9x). 
Execution trace in `develop`:  https://github.com/beehive-lab/TornadoVM/commit/fcdebe513dac9a06b569669f8322e72ed1725a55 
```bash
tornado --threadInfo -cp target/tornadovm-examples-1.0-SNAPSHOT.jar io.github.jjfumero.BlurFilter tornado device=0:2
WARNING: Using incubator modules: jdk.incubator.vector
Task info: blur.red
Backend           : OPENCL
Device            : …
```

[jit][cpu] Disable loop-interchange for CPU offloading

---

docs/source/installation.rst

Improve the documentation for the installation of TornadoVM on Windows 10/11
n/ a.
Link to the documentation.

[docs] Installation for Windows docs improved

---

etc/intel-oneapi-fpga.conf
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLCodeCache.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContextInterface.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLFPGAScheduler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLGridInfo.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLKernelScheduler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLDeviceContext.java

This PR provides a fix for the issue described in #401.
**Note**: This PR is tested on Intel Emulation mode. I do not have access to Xilinx FPGA to test it.
There are two identified problems:
1. In the `OCLCodeCache` class we have a method that checks if force compilation has been triggered, and the FPGA compilers for Intel are triggered to compile only if the check is true. This seems to have been an old check that we had from the time we had the `lookupbuffer` kernel, and we were waiting till all `LAUNCH` bytecodes that corresponds to all task indices (all tasks within a `TaskGraph`) are issued, in order to trigger the `forceCompilation()` method from the `TornadoVM` class. See [here](https://github.com/beehive-lab/TornadoVM/commit/e5048f0b90613f756a428faf8b1a9fd5511e57b5#diff-b7deca8312 …

[fix] Problem with FPGA execution for multiple tasks and the default scheduler

---

tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/compute/MatrixMultiplication2D.java

Minor fix to measure all timers in ns and then convert to seconds instead of measuring in milliseconds. 
n/a.
```bash
make
tornado -m tornado.examples/uk.ac.manchester.tornado.examples.compute.MatrixMultiplication2D
```

MxM example measured in ns to obtain a better reference on fast GPUs

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Float16.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Float2.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Float3.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Float4.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Float8.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/vectortypes/TestFloats.java

This PR adds Float<Size> vector operations to be operate with Int<Size> vector types.
Due to OpenCL/SPIR-V restrictions, the actual operation in native code can't be done using explicit vector types. But still it is possible to operate by accessing the individual fields of the vector.
Example could not use vector operations because of mismatch types. 
Compile and run for all backends:
```bash
tornado-test --printKernel -V uk.ac.manchester.tornado.unittests.vectortypes.TestFloats
```

Vector types for Float<With> with Int<Width> supported at the API-level

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/math/TornadoMath.java
tornado-examples/src/main/java/module-info.java
tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/vectors/DFTVector.java

This PR adds vector math operations for the `cos` and `sin` math functions. In addition, it expands the DFT example with the Vector API and applies a fix for the vector computation of the DFT. 
Fixes for the DFT application.
```bash
$ make
$ make tests
$  tornado --printKernel --enableProfiler console -m tornado.examples/uk.ac.manchester.tornado.examples.vectors.DFTVector vector8
```

Math operations for cos/sin with vector types supported

---

bin/compile

It checks for the `TORNADO_SDK` env variable upfront instead of compiling the whole TornadoVM and getting the error at the end, forcing to recompile the whole project. 
If the `TORNADO_SDK`  was not defined, TornadoVM only emits the error when maven finishes the Java build. 
```bash
$ make
$ bin/compile --jdk jdk21 --backend opencl
Checking TORNADO_SDK env variable ................ [ERROR] 
TORNADO_SDK env variable not defined
Suggestion (Linux and OSx): run `source setvars.sh`
Suggestion (Windows): run `setvars.cmd`
$ source setvars.sh
$ make 
ource setvars.sh 
 juan   feat/install/checker … 3  ~  tornadovm  TornadoVM  make
bin/compile --jdk jdk21 --backend …
```

[installer] check TORNADO_SDK upfront 

---

docs/source/conf.py
docs/source/index.rst
docs/source/installation.rst
docs/source/introduction.rst
docs/source/resources.rst

This PR updates the documentation with special attention to the installation steps for all supported OS.
n/ a.
```bash
make docs
google-chrome docs/build/html/index.html
```

Documentation Updated: Installation, landing page and resources

---

tornado-drivers/opencl-jni/src/main/cpp/source/SPIRVOCLDispatcher.cpp

For Apple devices, OpenCL supported is < 2.1.. Thus we can't call the function `clCreateProgramWithIL`. To avoid errors building the OpenCL backend, we bypass this function since this will be never call, unless Apple supports SPIR-V. 
This patch fixes build errors in TornadoVM with the OpenCL backend.
```bash
make 
make tests
```

Hotfix to bypass clCreateWithBinaryIL for non-spirv devices on OSx

---

tornado-drivers/opencl-jni/src/main/cpp/source/SPIRVOCLDispatcher.cpp

Build and compilation for Windows using MSVC++ compiler fixed.
TornadoVM build was broken.
```bash
make
make tests
make tests
```

[hotfix] Windows build fixed

---

README.md
bin/tornadovm-installer
docs/source/CHANGELOG.rst
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

Improvements
=============
- #402: Support for TornadoNativeArrays from FFI buffers.
- #403: Clean-up and refactoring for the code analysis of the loop-interchange.
- #405: Disable Loop-Interchange for CPU offloading..
- #407: Debugging OpenCL Kernels builds improved. 
- #410: CPU block scheduler disabled by default and option to switch between different thread-schedulers added.
- #418: TornadoOptions and TornadoLogger improved.
- #423: MxM using ns instead of ms to report performance.
- #425: Vector types for ``Float<Width>`` and ``Int<Width>`` supported.
- #429: Documentation of the installation process updated and improved.
- #432: Support for SPIR-V code generation and dispatcher using the TornadoVM OpenCL runtime.
Compatibility
=============
- #409: Guidelines to build the …

[release] TornadoVM 1.0.5

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/math/TornadoMath.java
tornado-assembly/src/bin/tornado-test
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXFPUnaryIntrinsicNode.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestIO.java

This PR fixes some failing unit-tests for `PTX`.
Here is a description of the reason of failing for every fixed test:
- `testTornadoMathCosPIDouble` and `testTornadoMathSinPIDouble`: `cos` and `sin` instructions support `f32` precision. So, we had to apply casting from `f64` to `f32` for those operators. For reference, see [here](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#floating-point-instructions).
- `testCopyInWithDevice`: This is a test that asserts whether there is a difference in the copy in data transfer timers, if the taskgraph is executed with the `withDevice` function, or not. This was due to a problem that was observed when the `withDevice` function was used, the behavior of an array that was defined with DataTransfer mode `FIRST_EXECUTION` was as if it …

Fix failing unit-tests for PTX in Jenkins

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDevice.java

This PR expands the SPIR-V support checker for OpenCL devices with multiple versions supported. 
If the OpenCL device to use contains as description multiple OpenCL devices, using the OpenCL `CL_DEVICE_IL_VERSION`, then the correct version was not detected. This PR fixes that. 
```bash
$ tornado --devices
```

[fix][rt] support for query multiple SPIR-V supported versions

---

Jenkinsfile

An update in the Jenkinsfile to build TornadoVM for all backends.
I also added two new stages for SPIR-V (1. with OpenCL runtime, 2. with Level Zero runtime) and fixed the index for the tornado devices because they were not matching with the title of their stage.

Update Jenkins to run SPIRV unit-tests for OpenCL and LevelZero runtimes

---

tornado-benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/BenchmarkRunner.java

List of benchmarks had one benchmark misspelled. 
n/ a.
```bash
tornado-benchmarks.py
```

Typo benchmark fixed

---

Makefile
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVBackendImpl.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVLevelZeroDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVLevelZeroPlatform.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVOCLDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVOpenCLPlatform.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVPlatform.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVRuntimeImpl.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVRuntimeType.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/SPIRVArchitecture.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/SPIRVHotSpotBackendFactory.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/tests/TestVM.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java

This PR adds an option in the `TornadoOptions` to select which runtime we want as default to dispatch SPIR-V code. 
By default. TornadoVM currently selects the OpenCL, but the user now can override this by using the following option:
- Use `-Dtornado.spirv.dispatcher=opencl` to select OpenCL as default.
- Use `-Dtornado.spirv.dispatcher=levelzero` to select LevelZero as default.
This is useful to pass, for example, all tests with another Runtime Dispatcher for SPIR-V. 
```bash
$ make tests-spirv-levelzero 
$ make tests-spirv-opencl
```
n/ a.
```bash
tornado --jvm="-Dtornado.spirv.dispatcher=opencl" …
```

Option to select the SPIR-V Runtime Dispatcher

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLAMDScheduler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLCPUScheduler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLFPGAScheduler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLGenericGPUScheduler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLKernelScheduler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLNVIDIAGPUScheduler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLScheduler.java

It seems that the new thread deployment strategy was introduced after the nvidia driver 550.67. So, not checking also for the minor version causes tornado-runtime to use the speciliazed nvidia scheduler and fails with:
```
[TornadoVM-OCL-JNI] ERROR : clEnqueueNDRangeKernel -> Returned: -54
```
```bash 
tornado -ea  --jvm "-Xmx6g -Dtornado.recover.bailout=False -Dtornado.unittests.verbose=True "  -m  tornado.unittests/uk.ac.manchester.tornado.unittests.tools.TornadoTestRunner  --params "uk.ac.manchester.tornado.unittests.loops.TestParallelDimensions"
```

Guard Nvidia GPU scheduler for minor version to prevent incorrect thread scheduling

---

tornado-assembly/src/bin/tornado-benchmarks.py

Add --properties option to display all dimensions and sizes for all benchmarks
Run the benchmark script using --properties option
`python %TORNADO_SDK%\bin\tornado-benchmarks.py --properties`

Update tornado-benchmarks.py, add --properties option

---

Jenkinsfile

This PR adds the new flag `-Dtornado.spirv.dispatcher` to select the runtime for running SPIR-V generated code, we have to add this option in our Jenkinsfile
As it was getting the "OpenCL" runtime was being selected even if the Level Zero device was explicitly added. The device id are taken from the Jenkins pipeline: 
```bash
Number of Tornado drivers: 3
[2024-06-17T15:38:47.423Z] Driver: SPIR-V
[2024-06-17T15:38:47.423Z]   Total number of SPIR-V devices  : 2
[2024-06-17T15:38:47.423Z]   Tornado device=0:0  (DEFAULT)
[2024-06-17T15:38:47.423Z] 	SPIRV -- SPIRV OCL - Intel(R) UHD Graphics 630
[2024-06-17T15:38:47.423Z] 		Global Memory Size: 58.5 GB
[2024-06-17T15:38:47.423Z] 		Local Memory Size: 64.0 KB …
```

Update Jenkinsfile regarding the execution of SPIR-V with the OpenCL and Intel LevelZero runtimes

---

tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVCodeCache.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVLevelZeroCodeCache.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVOCLCodeCache.java

This PR improves the handling of the SPIR-V binary by storing the intermediate binary in a temp directory per user. 
This can avoid some issues when running TornadoVM in a Compute/HPC cluster by multiple users. 
Directory permission issues due to sharing the same folder in some systems (e.g., Linux).
```bash
tornado-test --jvm="-Dtornado.spirv.dispatcher=levelzero" -V --debug uk.ac.manchester.tornado.unittests.foundation.TestFloats
tornado-test --jvm="-Dtornado.spirv.dispatcher=opencl" -V --debug uk.ac.manchester.tornado.unittests.foundation.TestFloats
```

[feat] SPIR-V binary stored in tmp directory per username

---

tornado-assembly/src/bin/tornado-test
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/virtual/TestVirtualDeviceFeatureExtraction.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/virtual/TestVirtualDeviceKernel.java

The CPU Virtual Tests were failing due to the thread -scheduler changes. Since the CPU scheduler now uses the Generic GPU scheduler, there is no distinction between them in regards with the Virtual Tests. This PR fixes this. 
Virtual Tests for CPU giving wrong results because the scheduler used is the Generic GPU scheduler. 
```bash
tornado -ea  --jvm "-Xmx6g -Dtornado.recover.bailout=False -Dtornado.unittests.verbose=True  -Dtornado.device.desc=${TORNADO_SDK}/examples/virtual-device-GPU.json -Dtornado.print.kernel=True -Dtornado.virtual.device=True -Dtornado.print.kernel.dir=${TORNADO_SDK}/virtualKernelOut.out"  -m …
```

CPU Virtual tests removed, since the scheduler between CPU/GPU is the same

---

README.md
docs/source/CHANGELOG.rst
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

- #442: Support for multiple SPIR-V device versions (>= 1.2).
- #444: Enabling automatic device memory clean-up after each run from the execution plan.
- #448: API extension to query device memory consumption at the TaskGraph granularity.
- #451: Option to select the default SPIR-V runtime.
- #455: Refactoring the API and documentation updated.
- #460: Refactoring all examples to use try-with-resources execution plans by default.
- #462: Support for copy array references from private to private memory on the hardware accelerator.
- #438: No writes for intermediate files to avoid permissions issues with Jenkins.
- #440: Update Jenkinsfile  for CI/CD testing.
- #443: Level Zero and OpenCL runtimes for SPIR-V included in the Jenkins CI/CD.
- #450: TornadoVM benchmark script improved to …

[release] TornadoVM v1.0.6

---

pom.xml

Motivated by issue #469, this PR adds the plugin to build the TornadoVM sources as well. This is paired with `updateMavenJarFiles` script for the releases to push to our maven repo the source files. This change will be effective from the next release. 
n/ a.
```bash
make 
```

Include plugin to include TornadoVM sources in the final build

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/math/TornadoMath.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestTornadoMathCollection.java

Some of the `FP64` version of the trigonometric functions within the `TornadoMath` class were missing.  Related issue #481 
n/ a,.
```bash
tornado-test -V -pk --fast uk.ac.manchester.tornado.unittests.math.TestTornadoMathCollection
```

TornadoMath double version of trigonometric functions added

---

bin/installer_config.py

Related issue #471. This PR adds the Temurin url for Windows.  I can't access to a Windows machine right now. 
@stratika , when you get the time, give it a try. 
n/ a.
[UPDATED INSTRUCTIONS]
```bash
python -m venv .venv
.venv\Scripts\activate.bat
.\bin\windowsMicrosoftStudioTools2022.cmd
python .\bin\tornadovm-installer --jdk temurin-jdk-21 --backend=opencl,ptx
tornado-test -V
```

Add URL for JDK Temurin Windows

---

tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXFPUnaryIntrinsicNode.java

This PR provides a fix for `radians` operations with `double` input types when PTX is used.
The problem was that the `radians` implementation is implemented as `(pi / 180) * degrees`, since there is no instruction. And in the compiler we had a check to ensure that it is only supported for `fp32`. 
In this PR, I added support for `fp64` types.
Build TornadoVM with PTX:
```bash
make BACKEND=ptx
```
Run:
```bash
tornado-test -V --printKernel --fast uk.ac.manchester.tornado.unittests.math.TestTornadoMathCollection#testTornadoMathRadiansDouble
```
Expected output:
```bash
WARNING: Using incubator modules: jdk.incubator.vector
.version 7.6 
.target sm_86 
.address_size …
```

[fix] Added fp64 kind for radians operations in PTX compiler

---

tornado-assembly/src/bin/tornado-test

This PR updates the whitelist to include a unit-test that fails in PTX due to driver's issue. The unit-test is passing on other systems, so I suggest including it in the white list of tests to avoid blocking the Jenkins pipeline.

[test] Update whitelist for PTX backend

---

tornado-assembly/src/bin/tornado-test
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestMemorySegmentsAsType.java

Following the discussion in #491, currently there is no proper error and exception handling when the user tries to run TornadoVM with a `MemorySegment` directly without using any of the `TornadoNativeTypes`.
This PR adds a test to trigger this behaviour, so we can discuss at which level we should throw the appropriate exception to prevent end-users to try to use `MemorySegments` directly.
```bash
tornado-test -V --debug uk.ac.manchester.tornado.unittests.api.TestMemorySegmentsAsType 
```

Add test to trigger unsupported input when user try to offload directly `MemorySegments` 

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/AccessorParameters.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraph.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraphInterface.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/PrebuiltTaskPackage.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/TaskPackage.java
tornado-benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/dgemm/DgemmTornado.java
tornado-benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/sgemm/SgemmTornado.java
tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/arrays/ArrayAddIntPrebuilt.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/analyzer/TaskUtils.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/PrebuiltTask.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/atomics/TestAtomics.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/prebuilt/PrebuiltTest.java

Draft PR - > Proposal to simplify the prebuilt-task API. 
Since we split Task-Graph into different data structures for definition and execution, we do not need all scheduling arguments in the prebuilt task API. This PR proposes a simplification of the Prebuilt Task API for:
1) Create Accessors to define data and its own accessor to the kernel. This is similar to SYCL and oneAPI. 
2) Remove the scheduling parameters from the Prebuilt-Task Graph. This information is stored in a GridScheduler that is passed at a later stage to the execution plan. 
As an example:
```java
// Define accessors for each parameter
AccessorParameters accessorParameters = new AccessorParameters(3);
accessorParameters.set(0, a, Access.READ_ONLY);
accessorParameters.set(1, b, Access.READ_ONLY); …
```

[feat][api] Prebuilt API redesign and simplification

---

Makefile
tornado-assembly/src/bin/tornado-test

Testing script runs the complete unit-test suite when is invoked. The test suite contains some test that they try to stress the device memory or rely on stable internet connection (high timeout). Thus, testing the whole suite during local development can cause  overhead.
This PR add an option in the test script to do a quick pass, by skipping these tests that cause they delay. This option by default is disabled and they user needs to explictly add it.
```bash
make jdk21 
tornado-test --ea --verbose --quickPass
```

Add `quickPass` option to skip heavy tests in tornado-test script

---

bin/installer_config.py

It seems that the tornadovm-installer script was configured in the past with a problematic name for graalvm jdk21. I tried to install it now and I got the following message:
```bash
JDK not supported. Please install with one of the JDKs from the supported list
jdk21
graalvm-jdk-21
corretto-jdk-21
microsoft-jdk-21
mandrel-jdk-21
zulu-jdk-21
temurin-jdk-21
sapmachine-jdk-21
```
The problem is that in our documentation and in the help message printed by the script we use `graal-jdk-21` as a valid name. 
As a result, I reverted the name in order to restore the installation.
If it is applicable, check your changes …

[hotfix] TornadoVM installer script fixed to build with GraalVM JDK 21

---

docs/source/spirv-backend.rst
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVBackendImpl.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java

This PR adds a flag to indicate TornadoVM to use a device with SPIR-V < 1.2. 
By default is 1.2, and this is the minimum required, as OpenCL Intel and Level Zero implementations requires this version of SPIR-V. However, there are other implementation (e.g., Codeplay) which supports 1.0. 
Since not all the kernels will pass (e.g., not FP16), This must be explicitly enabled by the user. 
The new flag: `-Dtornado.spirv.version=1.2`
n/ a.
Using the [OneAPI Construction Kit](https://github.com/codeplaysoftware/oneapi-construction-kit) to dispatch SPIR-V code on the CPU:
Without the new flag, we can't see the SPIR-V device for CPU from Compute Aorta:
```bash
tornado …
```

[spirv] flag to be able to run with prev. versions of SPIR-V 1.2

---

README.md

README file updated to use badges for the corresponding versions and licenses.
n/ a.
No need to test. The badges will be automatically rendered on GitHub.

[docs] fix badges in the README file

---

tornado-drivers/spirv/pom.xml

Update the LevelZero JNI dependency with the new version 0.1.4. This new version brings passing constant parameters to Level Zero Kernels.
n/ a.
To use the new version:
```bash
$ rm -Rf levelzero-jni/ level-zero/
$ source setvars.sh
```

[deps] Level Zero JNI v0.1.4 updated

---

bin/compile
bin/installer_config.py
bin/tornadovm-installer

This PR sets the dependencies to build the SPIR-V backend using the tagged versions instead of the master branch. This facilitates installation and configuration of older version. 
n/ a. 
```bash
rm -Rf beehive-spirv-toolkit/*
rm -Rf levelzero-jni/*
rm -Rf level-zero/
make tests
```

[build][spirv] Download tagged versions for dependencies (spirv-toolkit and level zero JNI)

---

tornado-assembly/src/bin/tornado-test
tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/code/CodeUtil.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/backend/OCLBackend.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoTaskSpecialisation.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/phases/TornadoTaskSpecialisation.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/phases/TornadoTaskSpecialization.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/functional/TestLambdas.java

That is the fix for the first problem described in the issue: https://github.com/beehive-lab/TornadoVM/issues/521 . 
Namely primitive parameters can not be passed in passed in anonymous lambda expressions.
// EDIT: Juan
```bash
tornado-test -V uk.ac.manchester.tornado.unittests.functional.TestLambdas#testParameterUnboxing
```

Remove param pi nodes

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/SchedulableTask.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/common/TornadoDevice.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLBackendImpl.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContextInterface.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLDeviceContext.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXBackendImpl.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVBackendImpl.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVDeviceContext.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/tests/TestVM.java
tornado-examples/src/main/java/uk/ac/manchester/tornado/examples/arrays/ArrayAddInt.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/JVMMapping.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/TornadoVM.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoXPUDevice.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoExecutionContext.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/CompilableTask.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/PrebuiltTask.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/AbstractRTContext.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/ScheduleContext.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/common/TornadoTestBase.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/profiler/TestProfiler.java

This PR fixes the device switching in the runtime. Some configurations (e.g., multple SPIR-V device from multiple vendors, or multiple OpenCL providers with different type of devices) could cause device switching to the wrong device. 
This PR fixes the problem by comparing the device to switch based on the vendor information, rather than the logic names that TornadoVM sets to devices. This guarantees switching to the correct device. 
Described  above. 
I realised this error when having multiple implementations for the Compute Aorta (Codeplay) such as one for CPUs (x86_64) and another one for RISC-V. Both configurations share the same platform name. However, the …

Fix the device switching for all backends

---

tornado-assembly/src/bin/tornado-test

Following a leftover from previous PR regarding a double entry in the `tornado-test` script, this PR removes the second entry.
Lines 54 and 98.

[test] Removed double entry from tornado-test

---

README.md
docs/source/CHANGELOG.rst
docs/source/conf.py
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-assembly/src/bin/tornado-test
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

Improvements
=============
- #468: Cleanup Abstract Metadata Class.
- #473: Add maven plugin to build TornadoVM source for the releases.
- #474: Refactor `<X>TornadoDevice` to place common methods in the `TornadoXPUInterface`.
- #482: Help messages improved when an out-of-memory exception is raised.
- #484: Double-type for the trigonometric functions added in the `TornadoMath` class.
- #487: Prebuilt API simplified.
- #494: Add test to trigger unsupported features related to direct use of Memory Segments.
- #509: Add a quick pass configuration to skip the heavy tests during active development.
- #532: Improve thread scheduler to support RISC-V Accelerators from Codeplay.
- #533: Support for scalar values to be passed via lambda expressions as tasks.
- #538: `README` file updated.
- #539: …

[release] TornadoVM 1.0.7

---

README.md
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/exceptions/TornadoExecutionPlanException.java
tornado-assembly/src/bin/tornado-test
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/prebuilt/PrebuiltTests.java

Test required to run the GAIA/AERO project to use a specific device within a setup a multiple devices and backends installed. 
n/ a.
```bash
$ make BACKEND=opencl,ptx
$ tornado-test --threadInfo -V uk.ac.manchester.tornado.unittests.prebuilt.PrebuiltTests#testPrebuiltMutiBackend
Task info: s0.t0
Backend           : PTX
Device            : NVIDIA GeForce GTX 1050 GPU
Dims              : 1
Thread dimensions : [8, 1, 1]
Blocks dimensions : [8, 1, 1]
Grids dimensions  : [1, 1, 1]
Task info: s0.t0
Backend           : PTX
Device            : NVIDIA GeForce GTX 1050 GPU
Dims              : 1
Thread dimensions : [8, 1, 1]
Blocks dimensions : [8, 1, 1]
Grids dimensions  : …
```

Prebuilt API test using a multi-backend setup and selecting specific device

---

tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVBackendImpl.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java

It was observed that when having more than one SPIR-V devices, the following error was generated depending on the specified device of execution. 
```
Unable to compile task s0.t0 - add
The internal error is: [Error During the Task Compilation]: Index 1 out of bounds for length 1
Stacktrace: [tornado.drivers.spirv@1.0.8-dev/uk.ac.manchester.tornado.drivers.spirv.runtime.SPIRVTornadoDevice.compileTask(SPIRVTornadoDevice.java:191), tornado.drivers.spirv@1.0.8-dev/uk.ac.manchester.tornado.drivers.spirv.runtime.SPIRVTornadoDevice.installCode(SPIRVTornadoDevice.java:129), tornado.runtime@1.0.8-dev/uk.ac.manchester.tornado.runtime.interpreter.TornadoVMInterpreter.compileTaskFromBytecodeToBinary(TornadoVMInterpreter.java:664), tornado.runtime@1.0.8-dev/uk.ac.manchester.tornado.runtime.interpreter. …
```

Fix issue with multiple SPIR-V devices

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestMath.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestTornadoMathCollection.java

This PR adds a compiler flag for OpenCL which enables `math` unit-tests to pass on Integrated GPUs.
This is for the Integrated GPUs that support `FP64` operations. Otherwise, the message for unsupported operations is displayed and not an error in the result.
For example:
```bash
Running test: [34mtestMathAtan[0m               ................ [31m [FAILED] [0m
\_[REASON] expected:<0.7853981633974483> but was:<0.7470323434249905>
``` 
**Note:** I included only the `-cl-opt-disable` flag which was sufficient to compile the unit-tests that were breaking. There are more compiler flags that can be added via the `DEFAULT_OPENCL_COMPILER_FLAGS`. Some of them were available in previous commit points from the commit [ffddb98](https://github.com/beehive-lab/TornadoVM/commit/ffddb981441189b0124ab517b …

[fix] OCL compiler flags for math tests on Integrated GPUs

---

.gitignore
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoDeviceContext.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContext.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLDeviceContextInterface.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/OCLJIT.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/tests/TestOpenCLJITCompiler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLDeviceContext.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/virtual/VirtualOCLTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXCodeCache.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/tests/TestPTXJITCompiler.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/tests/TestPTXTornadoCompiler.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVDeviceContext.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/tests/TestSPIRVJITCompiler.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/JVMMapping.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoXPUDevice.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java

This PR fixes multi-threaded execution plans. The issue (see below) was related to the unsafe shared of the code cache. The code cache was applied per device context, which is shared across all execution plans that run on the same device. Instead, what we need is to create a code-cache per execution plan ID. 
The multi-threaded tests stop working due to unsafe sharing of the code-cache within the TornadoVM device context. 
For each backend:
```bash
tornado-test --jvm="-Dtornado.device.memory=2GB" -V --fast uk.ac.manchester.tornado.unittests.multithreaded.TestMultiThreadedExecutionPlans
```
Before we merge, apart from all unit-test, we should test Ray-Tracer and …

[fix] Shared Execution Context fixed when having Multi-Threaded Java applicatons

---

Jenkinsfile

Following the PR that was merged earlier in the kfusion repository ([here](https://github.com/beehive-lab/kfusion-tornadovm/pull/38)), I made the update for the running scripts of running `kfusion` with TornadoVM in Jenkins for exclusive backend (OpenCL, or PTX). As a note, SPIR-V is not supported in this use case.
The change affects only the Jenkinsfile.

[hotfix] Update the running scripts to run kfusion in Jenkins exclusively on one backend

---

README.md
docs/source/CHANGELOG.rst
docs/source/conf.py
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-assembly/src/bin/tornado-test
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

Improvements
============
- #565: New API call in the Execution Plan to log/trace the executed configuration plans.
- #563: Expand the TornadoVM profiler with Level Zero Sysman Energy Metrics.
- #559: Refactoring Power Metric handlers for PTX and OpenCL.
- #548: Benchmarking improvements.
- #549: Prebuilt API tests added using multiple backend-setup.
- Add internal tests for monitoring memory management [link](https://github.com/beehive-lab/TornadoVM/commit/0644225a641bd859372743b59d46c6c9a4613337).
Compatibility
=============
- #561: Build for OSx 14.6 and OSx 15 fixed.
Bug Fixes
==============
- #564: Jenkins configuration fixed to run KFusion per backend.
- #562: Warmup action from the Execution Plan fixed to run with correct internal IDs.
- #557: Shared Execution Plans Context fixed. …

[release] TornadoVM 1.0.8

---

Jenkinsfile

Lately, we have extended the time for full unit-tests per backend (currently around 37 minutes) due to some heavy tests. Therefore, in this PR, I have extended the timeout for unit-tests (and overall the pipeline) so that to be within a reasonable time period.

[Jenkins] Extend the timeout for unit-tests

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/executor/TestExecutor.java

Fix log/printing paths for default execution plans (when no new actions are invoked) .
NPE were launched for default execution plans. 
```bash
tornado-test -V uk.ac.manchester.tornado.unittests.executor.TestExecutor#test05
```

[fix] Print default execution plans

---

tornado-assembly/src/bin/tornado-test
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLBlockVisitor.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/branching/TestLoopConditions.java

This PR fixes the closing brackets for OpenCL kernels that contain if-conditions either before or in for-loops. 
It was observed that in some cases where there was an if-condition in a kernel that contained for-loop(s)  (e.g. before a for-loop, in an inner for-loop etc.) , either some closing brackets were missing or unnecessary additional closing brackets were included. With this PR, the code generation examines these cases and generates the correct brackets.
Run `tornado-test -V -pk uk.ac.manchester.tornado.unittests.branching.TestLoopConditions`
All unittests have been tested along with RayTracer and KFusion.

[OpenCL] Fix issues with brackets for if-conditions in for-loops

---

bin/compile

This PR forces the TornadoVM installation script to use a specific Level Zero version (v1.17.45) because the recent merge of the changes for the L0 specification 1.11 do not allow Intel integrated graphics to be recognized as Level Zero devices.
A relevant issue is opened in the level-zero repository: https://github.com/oneapi-src/level-zero/issues/209
To test this PR, you should have an Intel integrated graphics in your system, and to remove first any existing level-zero directories.
```bash
rm -rf level*
tornado --devices
```

[hotfix] Used a fixed Level Zero version for Intel integrated graphics

---

tornado-assembly/src/bin/tornado-test

This PR extends the `tornado-tests` script to print a summary of the tests that fail along with information about whether they are whilelisted or not. This way it's easy to track the failing tests without having to go through all the output of the `tornado-tests` script. 
Below is the output of the test script with the proposed extension:
```
==================================================
Unit tests report 
==================================================
{'[PASS]': 666, '[FAILED]': 5, '[UNSUPPORTED]': 46}
Coverage [PASS/(PASS+FAIL)]: 99.25%
Coverage [PASS/(PASS+FAIL+UNSUPPORTED)]: 92.89%
==================================================
FAILED TESTS
==================================================
uk.ac.manchester.tornado.unittests.foundation.TestIf#test06 - [WHITELISTED]: YES …
```

Print list of failed tests at the end of the tornado-tests script

---

tornado-assembly/src/bin/tornado

This PR removes all legacy options related to jdk 8 and 11 still present in the tornado scirpt.

Remove legacy jdk 8 and 11 options from the tornado script

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix3DDouble.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix3DInt.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix3DLong.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix3DShort.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/TornadoMatrixInterface.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/utils/LongOps.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/utils/StorageFormats.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/matrices/TestMatrixTypes.java

This PR provides support for int, double, long and short 3d arrays by creating new matrix classes.
The `TestMatrixTypes` unittest has been extended with tests for the new 3d types. 
To test run: 
`tornado-test -V uk.ac.manchester.tornado.unittests.matrices.TestMatrixTypes`

Extend type support for 3D matrices

---

.build/TornadoVM-Build.run.xml
.build/TornadoVM-Full-OpenCL-Build.run.xml
.build/TornadoVM-Tests.run.xml
.build/_internal_TornadoVM_Maven-cleanAndinstall.run.xml
bin/post_installation.py
bin/tornadovm-installer
docs/source/ide-integration.rst
tornado-assembly/src/bin/tornado-test

This PR (is an update of #445) and provides the following:
1. a fix in the `tornadovm-installer` script to install `cmake` and `maven` in the path that is compliant with the IDE xml configurations.
2. a fix in the `post-installation` script for building TornadoVM from IntelliJ in Windows OS. This is to trigger the pyInstaller for building the `tornado` executables.
3. update the documentation for the TornadoVM [read-the-docs](https://tornadovm.readthedocs.io/en/latest/ide-integration.html).
The idea is that now TornadoVM users can:
1. build TornadoVM (with one or more backends) from IntelliJ in all OSs (Linux, macOS, Windows).
A user can use the Python application (**TornadoVM-Build**) that is in the repository, and update the Python interpreter and all configurations as described in the …

Restore building/running TornadoVM from IntelliJ & update of documentation

---

tornado-assembly/src/bin/tornado

If the user runs `tornado` without any args it shows a cryptic error.
Now, with this change, by default it throws the helper menu similar to what `java` does.
```bash 
╰─cmd ➜ tornado
WARNING: Using incubator modules: jdk.incubator.vector
Error: Could not find or load main class None
Caused by: java.lang.ClassNotFoundException: None
```
```bash
tornado
```

Add helper menu by default when args are 0 to the tornado launcher script

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLScheduler.java

This PR fixes the issue #586 by selecting the right scheduler for the OpenCL thread-block dispatcher. 
The problem was the assumption that the minor version in NVIDIA drivers was sequential and incremental, even across different major versions. This PR fixes this issue. 
```bash
$ make BACKEND=opencl
$ make tests
$ tornado --threadInfo -m tornado.examples/uk.ac.manchester.tornado.examples.compute.MatrixMultiplication2D
```

[fix] NVIDIA Thread Scheduler for new NVIDIA drivers

---

tornado-assembly/src/etc/exportLists/common-exports
tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/compiler/phases/loops/TornadoPartialLoopUnrollPhase.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLMidTier.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXMidTier.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/SPIRVLIRGenerator.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/SPIRVLowTier.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/SPIRVMidTier.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/SPIRVNodeLIRBuilder.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/lir/SPIRVControlFlow.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/nodes/PartialUnrollNode.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/phases/PartialLoopUnrollPhase.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/meta/TaskDataContext.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/matrices/TestMatrices.java

This patch enhances the JIT compiler with a phase for partial loop unroll and full loop unroll suggestions for SPIR-V.
In a nutshell: 
1. It introduces a full loop unroll suggestion for the SPIR-V compiler. 
2. It introduces partial loop unroller for the PTX compiler.
3. It fixes the partial loop unroll configuration for OpenCL 
4. It enables partial loop unroll for OpenCL 
Note that the partial loop unroll flag is **off** by default, since more experimentation is needed.  If `ON`, there are some tests failing (~14) due to some failures in the Graal JIT compiler. However, for some compute applications this optimisations must be beneficial, and, in the case of the SPIR-V, it works in combination of SPIR-V unroll suggestions as well as explicit loop unroll. 
n/ a.
Mark the backends affected …

Enable Partial Loop Unroll for all Backends

---

bin/installer_config.py
bin/tornadovm-installer
docs/source/installation.rst

This partially enables the installation for RISC-V 64 on Linux systems. This patch can be combined with a new patch to be able to compile and run on RISC-V. The patch removes the dependency to `cmake-maven` due to unsupported RISC-V architecture. 
Once the plugin supports RISC-V, we can drop the external patch. 
This patch also includes a new JDK installation for Liberica JDK 21. This JDK includes a port for RISC-V 64. 
```bash
./bin/tornadovm-installer --jdk liberica-jdk-21 --backend=opencl
```
n. a
On a RISC-V platform:
```bash
wget https://gist.githubusercontent.com/jjfumero/c191f7e69a653c4f59f238d5856201aa/raw/d79af888a9873f8a3b44e4cc35a8ae382684cdb2/apply-riscv …
```

RISC-V 64 Port Enabled

---

tornado-assembly/src/bin/tornado-test
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLLowTier.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/InfinityReplacementPhase.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXLowTier.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/phases/InfinityReplacementPhase.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/SPIRVLowTier.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/phases/InfinityReplacementPhase.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/MMwithBytes.java

There was a bug when generating code for the constant values `Float.POSITIVE_INFINITY` and `Float.NEGATIVE_INFINITY` from the Float class. Using these values caused the compiler to generate OpenCL code with Infinity and -Infinity constants, which are not valid OpenCL intrinsics.
This fix replaces Float.POSITIVE_INFINITY and Float.NEGATIVE_INFINITY with `1.0f / 0.0f` and `-1.0f / 0.0f` respectively, which are the proper representations of positive and negative infinity in OpenCL.
```bash
make jdk21 
tornado-test  -V uk.ac.manchester.tornado.unittests.compute.MMwithBytes
```

[Fix] Replace Invalid OpenCL Representation of Infinity Constants for `Float.POSITIVE_INFINITY` and `Float.NEGATIVE_INFINITY`

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLBlockVisitor.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompilationResultBuilder.java

This PR fixes issue #590.
After close inspection the problem was that for FPGAs, we apply a compiler optimization for loop flattening of the outermost for loop. In this case, the `OCLBlockVisitor.java` class did not account for the flattened loop and was emitting the closing bracket.
```bash
make && make fast-tests
tornado-test -V uk.ac.manchester.tornado.unittests.branching.TestLoopConditions
```
In my case the FPGA device is device `0:4`. To test on FPGAs kernels, run: 
```bash
rm -rf fpga-source-comp/ && tornado --igv --jvm "-Ds0.t0.device=0:4 -Xmx20g -Xms20g" --printKernel --threadInfo -m tornado.examples/uk.ac.manchester.tornado.examples.dynamic.DFTMT …
```

[hotfix] FPGA kernels generate an extra bracket

---

tornado-api/src/main/java/module-info.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/ExecutionPlanType.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutor.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/plan/types/WithAllGraphs.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/plan/types/WithGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/executor/TestExecutor.java

This PR extends the `TornadoExecutionPlan` API with a new method to select a graph to launch from a multi-graph execution plan configuration. This type of code is useful when we need to share context (e.g., command queues, cuda streams, code cache, etc) for the whole execution plan, but we only need to execute a task-graph at the time. 
The two methods added are as follows:
```java
try (TornadoExecutionPlan executionPlan = new TornadoExecutionPlan(tg1.snapshot(), tg2.snapshot())) {
// Select graph 1 (tg2) to execute
// Once selected, every time we call the execute method,
// TornadoVM will launch the passed task-graph.
executionPlan.withGraph(1).execute();
// Select the graph 0 (tg1) to execute
executionPlan.withGraph(0).execute();
// Select all graphs (tg1 and tg2) to execute.
// Since …
```

[Feature] Select graph from a multi-graph execution plan to launch. 

---

README.md
bin/tornadovm-installer
docs/source/CHANGELOG.rst
docs/source/conf.py
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

Improvements
=============
- #573: Enhanced output of unit-tests with a summary  of pass-rates and fail-rates.
- #576: Extended support for 3D matrices.
- #580: Extended debug information for execution plans.
- #584: Added helper menu for the ``tornado`` launcher script when no arguments are passed.
- #589: Enable partial loop unrolling for all backends.
- #594: Added RISC-V 64 CPU port support to run OpenCL with vector instructions RVV 1.0 (using the Codeplay OCK Toolkit).
- #598: OpenCL low-level buffers tagged as read, write and read/write based on the data dependency analysis.
- #601: Feature to select an immutable task graph to execute from a multi-task graph execution plan.
Compatibility
=============
- #570:  Extended timeout for all suite of unit-tests.
- #579: Removed legacy JDK …

[release] TornadoVM 1.0.9

---

docs/source/installation.rst

Documentation for building TornadoVM for RISC-V platforms updated to the 1.0.10-dev version.
n/ a.
```bash
make docs
```

[docs] Updated instructions for RISC-V

---

tornado-assembly/src/bin/tornado-benchmarks.py

This PR fixes some typos in the data sizes that regard some sizes not being power of 2. The issue was observed when I ran the script for the `SPIR-V` backend with `LevelZero` and took significantly more than expected to finish.
So, I open this PR to restore the sizes to be in the power of 2.
You can run the `tornado-benchmarks.py` script with full sizes to test the new values. It may take few hours depending on the number of iterations and devices that you have in your system.
```bash
tornado-benchmarks.py --full
```

[fix] Update data sizes in tornado-benchmarks.py

---

docs/source/spirv-backend.rst
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLPragmaUnroll.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVBackendImpl.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVOpenCLPlatform.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/SPIRVRuntimeImpl.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java

**Updated** See discussions below.
This PR extends TornadoVM to select individual runtimes for dispatching and managing SPIR-V. To do so, this PR introduces new option (`-Dtornado.spirv.runtimes`) 
To select **only** the level zero port with SPIR-V.
```bash
tornado <flags> --jvm="-Dtornado.spirv.runtimes=levelzero " <program>
```
To select **only** the OpenCL port with SPIR-V:
```bash
tornado <flags> --jvm="-Dtornado.spirv.runtimes=opencl " <program>
```
To select both OpenCL and SPIR-V. The default one is the first in the list. 
```bash
tornado <flags> --jvm="-Dtornado.spirv.runtimes=opencl,levelzero " <program>
```
Developers can select either `opencl` or `levelzero` as a default dispatcher.
The main obstacle was that TornadoVM required both Level Zero and OpenCL runtimes to work with …

[feat] Individual selection of Level Zero and/or OpenCL runtimes for SPIR-V 

---

bin/installer_config.py

Update Maven Dependency 
n/ a.
```bash
./bin/tornadovm-installer --jdk jdk21 --backend=opencl
```

Maven dependency updated

---

bin/compile

Enable colours in maven build
Not sure why, but newer versions of Fedora colours were disabled. We can force this to be enabled.
```bash
make
```

Enable colours in maven build

---

Jenkinsfile

This PR updates the flag defined in the Jenkinsfile based on the refactored flag name. 
`--skipSequential` is replaced with `--skipSerial`

[fix] Update Benchmark flag in Jenkinsfile

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Half16.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Half2.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/vectors/Half8.java
tornado-benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/BenchmarkDriver.java
tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/TornadoBufferProvider.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/sketcher/TornadoSketcher.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/PrebuiltTask.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/ComputeTests.java

This PR does not touch any production code. It only applies fixes for the checkstyle (e.g., unused imports, splitting initialization of two variables in separate lines, etc.)
If you try the following command, you will see several errors:
```bash
```
```bash
```

[style] Fix check style of source code

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLUnary.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/DecAtomicNode.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/IncAtomicNode.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoAtomicsScheduling.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/atomics/TestAtomics.java

This PR provides one fix and one extension:
- It fixes the `incrementAndGet` functionality in OpenCL because the OpenCL implementation of the `atomic_inc` function returns the [old value](https://manpages.debian.org/buster/opencl-1.2-man-doc/atom_inc.3clc.en.html) and not the incremented result.
- It adds two plugins for `getAndIncrement` and `getAndDecrement` functions along with the respective tests.
- It enables the functions that use the `Kernel API` for expressing parallelism, to also use the `AtomicInteger` object. However, this is allowed, only if it is passed as an argument to the method. This is according to the design that is currently applicable at the methods that use the `Loop Parallel` API.
- It adds in total five new unit-tests that assess the `incrementAndGet` , …

[fix] Atomic operations in OpenCL with the Kernel API

---

README.md
bin/tornadovm-installer
docs/source/CHANGELOG.rst
docs/source/conf.py
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-assembly/src/bin/tornado-test
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

- #608: Selective execution with multiple SPIR-V runtimes (either OpenCL, Intel Level Zero, or both) to unlock execution on RISC-V systems. 
- #611: Support of ``HalfFloat`` for Matrix Types (``FP16`` -> ``FP16``).
- #607: WSL installation and configuration updated for WSL Ubuntu 24 LTS and Windows 11.
- #609: Documentation and patch for RISC-V64 updated.
- #610: Maven dependency updated
- #612: Re-enable colours in maven builds on Linux. 
- #606: Fix data sizes in benchmark suite.
- #613: Fix code formatter.
- #614: Fix flags for the benchmark pipeline in Jenkins. 
- #615: Fix code style based on the formatter. 
- #616: Fix atomics for the Kernel API and the OpenCL backend.
If it is applicable, check your changes …

[release] v1.0.10

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLLIRStmt.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLConvertHalfToFloat.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/TornadoHalfFloatReplacement.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/plugins/PTXGraphBuilderPlugins.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/lir/PTXLIRStmt.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/PTXConvertHalfToFloat.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/phases/TornadoHalfFloatReplacement.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/plugins/SPIRVGraphBuilderPlugins.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/nodes/SPIRVConvertHalfToFloat.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/phases/TornadoHalfFloatReplacement.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/ComputeTests.java

This PR enables mixed precision matrix multiplication, where the input matrices contain half float values and the results are stored in an FP32 matrix. 
Run `tornado-test -V uk.ac.manchester.tornado.unittests.compute.ComputeTests#testHalfFloatToFloatMatrixMultiplication`
and 
`tornado-test -V uk.ac.manchester.tornado.unittests.compute.ComputeTests#testHalfFloatToFloatMatrixMultiplication2`

Support Mixed Precision Matrix Multiplication  (FP16 to FP32)

---

tornado-assembly/src/bin/tornado-test

This PR does not have any change in the production code. It only registers six unit-tests from the Atomics test suite in the white list. Theses tests are failing in some devices (Integrated Graphics), but pass on other devices. The kernels are correct, so the issue is attributed to precision errors, or driver issues.
The problem is observed in the Jenkins pipeline.

[test] Update whitelisted unit-tests with the new atomic tests

---

docs/source/installation.rst

Build instructions for RISC-V updated
n/ a.
For RISC-V Boards:
```bash
wget https://gist.githubusercontent.com/jjfumero/c191f7e69a653c4f59f238d5856201aa/raw/748f71a1871f3bf839c8889a31c09c55f6969186/apply-riscv-patch.sh
bash apply-riscv-patch.sh 
tornado --version
```

[docs] RISC-V Build instructions updated

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoDeviceMap.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestDevices.java

This PR fixes an issue with device filtering and the unittests associated with it. Besides, it adds new new functions to the `TornadoDeviceMap` API to easily query devices by a specific type, or a specific name. 
Fix the filtering of backends and devices. 
```bash
tornado-test -V uk.ac.manchester.tornado.unittests.api.TestDevices
```

Device Filtering Fixed + New filters by device type and device names

---

tornado-assembly/src/bin/tornado-test
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestDevices.java

This PR includes in the whitelist the unit-tests that filter devices. This is ok if they fail, since it queries specific devices. 
Fix Jenkins pipeline test regression.
```bash
tornado-test -V uk.ac.manchester.tornado.unittests.api.TestDevices
```

Hotfix for the whitelist of some test-devices unittests

---

Makefile
Makefile.mak
bin/compile
bin/tornadovm-installer

This PR adds a new rule in the Makefile for forcing maven to run with one thread. Additionally, it exposes a user parameter in the `compile` script and the `tornadovm-installer` script to trigger this rule.
See here the help menu:
```bash
./bin/tornadovm-installer                                                          
usage: tornadovm-installer [-h] [--version] [--jdk JDK] [--backend BACKEND] [--listJDKs] [--javaHome JAVAHOME] [--polyglot] [--mvn_single_threaded]
TornadoVM Installer Tool. It will install all software dependencies except the GPU/FPGA drivers
options:
-h, --help            show this help message and exit
--version             Print version of TornadoVM
--jdk JDK             Select one of the supported JDKs. Use --listJDKs option to see all supported ones.
--backend …
```

Build with maven in single-threaded mode

---

tornado-assembly/src/bin/tornado-test
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestChainOfGridSchedulers.java

This patch adds a new unit test, `TestChainOfGridSchedulers`, which verifies the execution of multiple task graphs using different `GridScheduler` configurations within a single `TornadoExecutionPlan`. The test ensures that distinct task graphs can be scheduled and executed correctly with separate work-group configurations.
The order in which methods are chained when configuring and executing task graphs within a `TornadoExecutionPlan` is crucial. The correct sequence should be choosing the task graph first, then applying the `GridScheduler`.
The following approach is **incorrect** because it first sets the GridScheduler and then selects the task graph:
```java
executionPlan.withGridScheduler(gridScheduler1).withGraph(0).execute(); // Execute TaskGraph 1 …
```

Add Unit Test for Executing Multiple Task Graphs with Different Grid Schedulers

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/DebugInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java

This PR includes the object size information and batch size information for all objects in the TornadoVM BC interpreter.
It also refactors the debugging from the `TornadoVMInterpreter`.
n/ a.
```bash
make
tornado-test -V -pbc uk.ac.manchester.tornado.unittests.foundation.TestFloats
```

[logs] Bytecode interpreter with object size

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/LocalArrayNode.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/plugins/PTXGraphBuilderPlugins.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/nodes/LocalArrayNode.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/plugins/SPIRVGraphBuilderPlugins.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/nodes/LocalArrayNode.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/codegen/CodeGenTest.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsDoublesKernelContext.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsFloatsKernelContext.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsIntegersKernelContext.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/kernelcontext/reductions/TestReductionsLongKernelContext.java

This PR provides a hotfix regarding the allocation of local memory in the 3 backends (OpenCL, PTX, SPIR-V). The issue is described in #634.
I have added several uni-tests to test the update in the compiler plugins for various data types.
**Note:** In OpenCL, the dynamic data size for the definition of a local memory array, is not supported. Therefore, as a workaround we pass the size as argument in the method.
The issue was that the compiler plugins were requiring the input size to be a constant.
Note that for SPIR-V, some unit-tests are classified as unsupported due to FP64 not been supported for the Integrated Graphics.
In OpenCL:
```bash
make BACKEND=opencl …
```

[hotfix] Update inner node for local memory allocation to be ValueNode instead of ConstantNode

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLAtomicsBuffer.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/mm/OCLMemoryManager.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java

It forces to clean up all resources (e.g., all GPU memory used) when the `ExecutionPlan` resource is closed. 
The only exception is when using constant memory (as in CUDA constant) and atomics, which in TornadoVM, these
are separated memory regions handler by the device memory manager. 
In future versions of TornadoVM, we should improve these handler by taking into account the execution plan IDs, we memory management can be further improved. 
When running with large data sets with multiple execution plans, TornadoVM tends to lock memory to reuse as much as possible. However, when a resource (execution plan) is closed, we can free all resources associated to an execution plan, and make more space for new execution plans. 
This is needed to run GAIA code under the AERO EU project. 
Mark the …

[rt] Memory dealloc by default when closing an execution plan resource

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/math/TornadoMath.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/asm/OCLAssembler.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLGraphBuilderPlugins.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/plugins/OCLMathPlugins.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/lir/OCLBuiltinTool.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/nodes/OCLFPUnaryIntrinsicNode.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/plugins/SPIRVMathPlugins.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/lir/SPIRVBuiltinTool.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/nodes/SPIRVFPUnaryIntrinsicNode.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestTornadoMathCollection.java

Expand the TornadoVM Math function with `asinh` and `acosh` for the OpenCL and SPIR-V backends. 
n/ a.
- [] PTX
```bash
make
tornado-test -pk -V uk.ac.manchester.tornado.unittests.math.TestTornadoMathCollection#testTornadoMathCosh
tornado-test -pk -V uk.ac.manchester.tornado.unittests.math.TestTornadoMathCollection#testMathASinh
```

Compiler Plugins for `acosh` and `asinh` math functions 

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutor.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestSharedBuffers.java

There was an issue with the shared buffer functionalty that it was taking into account that shared buffers might not be present in all tasks of taskgraph. This is it was causing negative allocation for some tests. Also, it adds tests to force  buffers to be copied out but adding intermediate dummy tasks. 
```bash 
tornado-test   -V uk.ac.manchester.tornado.unittests.api.TestSharedBuffers
```

[hotfix] Fix to prevent issue with shared buffer allocation when not all buffers are present in args

---

tornado-assembly/src/bin/tornado-test

Change fast mode to live mode in tornado-test
n/a/
```bash
tornado-test -V --live uk.ac.manchester.tornado.unittests.api.TestSharedBuffers
```

[refactor] Change fast mode to live mode in tornado-test

---

tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXStream.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/mm/PTXMemorySegmentWrapper.java

Memory region mapping with offsets fixed
PTX assumes offset of 4 bytes, which was a leftover from the original PoC. 
```bash
make BACKEND=ptx
tornado-test -pbc --threadInfo -V uk.ac.manchester.tornado.unittests.pointers.TestCopyDevicePointers
```

[ptx] Memory region mapping with offsets fixed

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/DebugInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java

This PR improves the logging for bytecode for deallocation. It now it includes information on status (free vs persisted).
This is needed to debug the actual action of the dealloc bytecode.
Dealloc that is actuall executed uses the same color with the other bytecodes.
Dealloc with empty action uses  differenct color. 
Also, status uses different color for readability.
```bash
tornado-test --printBytecodes -V uk.ac.manchester.tornado.unittests.api.TestSharedBuffers 
```

[loging] Enhance deallocation logging to include materialization of action

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoVMBytecodeBuilder.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/nodes/OnDeviceObjectNode.java

Fix incorrect object index in onDevice bytecode generation. The system was using the OnDeviceObjectNode's ID instead of the wrapped ObjectNode's index, causing multiple objects to be processed with the same index. This resulted in redundant operations on the first object while subsequent objects were ignored.
```bash
tornado-test --printBytecodes -V uk.ac.manchester.tornado.unittests.api.TestSharedBuffers#testMultipleSharedObjects
```
Expected output:
```bash 
Interpreter instance running bytecodes for:   [NVIDIA CUDA] -- NVIDIA GeForce RTX 3070 Running in thread:  main
bc:  ALLOC uk.ac.manchester.tornado.api.types.arrays.IntArray@3a0baae5 on   [NVIDIA CUDA] -- …
```

[hotfix] Object repetition with shared buffers on ON_DEVICE bytecodes

---

tornado-assembly/src/bin/tornado-test

This PR adds one test from the new unit-tests in white list. The reason is that in some systems (including the Jenkins server) it has inconsistent behavior, which is most likely attributed to the specific driver version. 
In other systems, it is stable.
Not applicable

[test] Add loop condition test in white list

---

README.md
bin/tornadovm-installer
docs/source/CHANGELOG.rst
docs/source/conf.py
docs/source/installation.rst
pom.xml
tornado-annotation/pom.xml
tornado-api/pom.xml
tornado-assembly/pom.xml
tornado-assembly/src/bin/tornado-test
tornado-benchmarks/pom.xml
tornado-drivers/drivers-common/pom.xml
tornado-drivers/opencl-jni/pom.xml
tornado-drivers/opencl/pom.xml
tornado-drivers/pom.xml
tornado-drivers/ptx-jni/pom.xml
tornado-drivers/ptx/pom.xml
tornado-drivers/spirv/pom.xml
tornado-examples/pom.xml
tornado-matrices/pom.xml
tornado-runtime/pom.xml
tornado-unittests/pom.xml

#620: Support of computation with mixed precision ``FP16`` to  ``FP32`` for matrix operations.
#622: New API to allow buffer mapping between two different buffers on the hardware accelerator.
#624: Enhanced TornadoVM profiler with correct information for the ``UNDER_DEMAND`` transfer to host data. 
#627: New feature to persist data on the hardware accelerator, and consume data already allocated on the hardware accelerator.
#630: Support for atomics using the kernel API for OpenCL and PTX backends. 
#636: TornadoVM bytecode logging improved. 
#642: Math functions extended: ``acosh`` and ``asinh`` supported for OpenCL and SPIR-V.
#645: Memory deallocations improved. Action by default when closing the ``TornadoExecutionPlan`` resource.
#625: Documentation to build on RISC-V updated.
#632: …

[release] TornadoVM 1.1.0

---

docs/source/installation.rst

With every new version of TornadoVM we need to update the links for the RISC-V patch installer. This PR provides the updated links. 
n/ a.
```bash
$ wget https://gist.githubusercontent.com/jjfumero/c191f7e69a653c4f59f238d5856201aa/raw/f91c67f43e4da14eb80b79e88441604d9c6ba829/apply-riscv-patch.sh
$ bash apply-riscv-patch.sh
```

[riscv] Build patches for RISC-V fixed for v1.1.0

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java

The condition that checks if a deallocation is perfomed was the reversed, so it was causing printing freed buffers as persisted and persited as freed.

[hotfix] Fix reverse condition that causes revert bytecode logging

---

tornado-assembly/src/bin/tornado
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/RuntimeUtilities.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java

This PR adds functionality to dump the TornaoVM bytecodes into a log file for debugging purposes or to visualize them directly with [TornadoVM Bytecode Analyzer](https://github.com/mikepapadim/tornadovm-bytecode-analyzer).
Also, extend the tornado running script with support for:
```bash
--dumpBC PATH/FILENAME 
```
```bash
tornado-test --jvm="-Dtornado.dump.bytecodes.dir=$(pwd)" -pbc -V uk.ac.manchester.tornado.unittests.api.TestSharedBuffers#testMultipleSharedObjects
tornado --dumpBC PATH/FILENAME   -m …
```

[feature] Add functionality to dump TornadoVM internal bytecodes to a log file

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/ImmutableTaskGraph.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraph.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutor.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoTaskGraphInterface.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/grid/TestGridScheduler.java

This PR fixes the checker for the task-graph names needed for the `GridScheduler.` There was a bug when we have multiple task-graphs in a single execution plan. With this PR, the global check/control  is done at the execution plan level , rather the task-graph. 
See below
```bash
tornado-test -V -pk --threadInfo uk.ac.manchester.tornado.unittests.grid.TestGridScheduler#testMultiTaskGraphs
```

[Fix] Grid Scheduler Name checker for execution plans with multiple task-graphs

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/memory/DeviceBufferState.java
tornado-drivers/drivers-common/src/main/java/uk/ac/manchester/tornado/drivers/common/TornadoBufferProvider.java
tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/runtime/OCLTornadoDevice.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/runtime/PTXTornadoDevice.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/runtime/SPIRVTornadoDevice.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/XPUDeviceBufferState.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java

Currently,  TornadoVM performs an allocation and deallocation for every batch of the input data. This PR proposes reusing the buffers that are allocated after the first allocation for all the batches of the same size that will follow and deallocating when the final batch of said size concludes. If the batches are not even, there is a final allocation-deallocation sequence for the remaining batch, as in develop. Below is an example of the bytecodes generated for the unittest `uk.ac.manchester.tornado.unittests.batches.TestBatches#test300MB` in develop and in the current PR. 
== develop
```
Interpreter instance running bytecodes for:   [NVIDIA CUDA] -- NVIDIA GeForce RTX 4070 Laptop GPU Running in thread:  main
bc:  ALLOC uk.ac.manchester.tornado.api.types.arrays.FloatArray@5adb0db3 on …
```

Optimize number of batch allocations

---

docs/source/flags.rst
tornado-assembly/src/bin/tornado
tornado-assembly/src/bin/tornado-test
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/virtual/TestVirtualDeviceFeatureExtraction.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/virtual/TestVirtualDeviceKernel.java

This PR updates the documentation page regarding the TornadoVM flags. It provides the clarification suggested in #665 and refactors one TornadoVM JVM flag the `-Dtornado.print.kernel` to `-Dtornado.printKernel` in order to follow the same name convension with the Python CLI flag `--printKernel`. Similar approach is already in place for the `-Dtornado.threadInfo` flag.
To read the updated docs run:
```bash
make docs
```

[docs] Update documentation of the TornadoVM flags

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/DebugInterpreter.java

Previsouly, `TRANSFER_HOST_TO_DEVICE_ONCE` when executed multiple times didn't capture an empty action when data is already on-device from previous execution. This PR adds an extract field to mark the status for this bytecode as `Transferred` or `Present`.
Before:
```bash
Interpreter instance running bytecodes for:   [NVIDIA CUDA] -- NVIDIA GeForce RTX 3070 Running in thread:  main
bc:  ALLOC VectorInt2 <16> on   [NVIDIA CUDA] -- NVIDIA GeForce RTX 3070 , size=184, batchSize=0
bc:  ALLOC VectorInt2 <16> on   [NVIDIA CUDA] -- NVIDIA GeForce RTX 3070 , size=184, batchSize=0
bc:  ALLOC VectorInt2 <16> on   [NVIDIA CUDA] -- NVIDIA GeForce RTX 3070 , size=184, batchSize=0
bc:  TRANSFER_HOST_TO_DEVICE_ONCE  [Object Hash Code=0x4748a0f9] VectorInt2 <16> on   [NVIDIA CUDA] -- NVIDIA GeForce RTX …
```

Improve output on `TRANSER_TO_DEVICE_ONCE` bc with marking non-executed actions

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/matrix/Matrix4x4Float.java
tornado-benchmarks/src/main/java/uk/ac/manchester/tornado/benchmarks/GraphicsKernels.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/slam/GraphicsTests.java

This PR includes the following:
- Refactoring of the access modifiers for the `set` and `get` methods of the `Matrix4x4Float` type. Those methods are regularly public in order to be accessed by programmers.
- Refactoring of the `GraphicsKernel` class, in order to import the `TornadoMath` class instead of the inner method name. This change makes those TornadoVM tasks compatible with the implementation in [TornadoInsight](https://github.com/beehive-lab/tornado-insight) (the IntelliJ plugin). 
- Refactoring of test to use constant defined in the inner class.
The main problem was the incompatibility with TornadoInsight, which revealed that the `Matrix4x4Float` type could not be properly set/get by programmers.
If it …

Refactoring of the Matrix4x4Float type

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoGraphBuilder.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoVMBytecodeBuilder.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/TornadoVMBytecodes.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/graph/nodes/PersistedObjectNode.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/DebugInterpreter.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java

This PR addresses an issue with object persistence in TornadoVM's bytecode generation. Objects marked for persistence in the task graph were not properly captured by the existing bytecodes, leading to potential memory management issues in subsequent task graph executions.
The fix extends the bytecode generation to explicitly capture the state of persisted objects using a new `PERSIST_BUFFER` bytecode operation, ensuring that objects intended for reuse across multiple task graph executions are properly tracked and maintained.
Before the fix:
```bash
Interpreter instance running bytecodes for:   [NVIDIA CUDA] -- NVIDIA GeForce RTX 3070 Running in thread:  main
bc:  ALLOC uk.ac.manchester.tornado.api.types.arrays.IntArray@3a0baae5 on   [NVIDIA CUDA] -- NVIDIA GeForce RTX 3070 , size=88, …
```

[feature] Extend TornadoVM bytecodes with `PERSIST_BUFFER` bc to improve tracking of an object lifecycle

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/RuntimeUtilities.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/common/TornadoOptions.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java

This PR provides a small refactoring to fix the issue of printing the bytecodes in the console when the programmer wants to only store them in a file. Additionally, it fixes an issue with the ANSI espace characters during the logging of bytecodes.
To simplify this procedure, I added a method `TornadoOptions.LOG_BYTECODES()` which is now used in the TornadoInterpreter class to log the bytecodes. This method is true when the programmer has used:
- the option to print the bytecodes in console, via`-Dtornado.print.bytecodes=True`.
- or the option to save the bytecodes in a file, via `-Dtornado.dump.bytecodes.dir=<path-to-file>`.
Regarding the issue with the escape characters this affects the bytecode analyzer. 
A snapshot of the issue when bytecodes are saved in file:
```bash
[34mInterpreter …
```

Refactoring the Configuration of Logging the TornadoVM Bytecodes 

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/ImmutableTaskGraph.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraph.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TaskGraphInterface.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutionPlan.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutor.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoTaskGraphInterface.java
tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/tasks/TornadoTaskGraph.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/api/TestSharedBuffers.java

Currently, with ```consumeFromDevice(taskgraphName, objects...)```, users must explicitly specify the source task graph from which objects will be consumed. This creates a rigid dependency structure where objects can only be consumed from a single, named task graph. This limits complex pipeline designs where objects might be updated by different task graphs in varying execution patterns.
This PR introduces the following enhancements:
* Automatic Task Graph Tracking: Added support for tracking the last executed task graph in the execution plan, eliminating the need to explicitly name source task graphs.
* Simplified API: Introduced a new consumeFromDevice(objects...) method that automatically uses the last executed task graph as the source, making the API more intuitive and reducing …

Support for updating object state from directly from the last executed task-graph 

---

tornado-runtime/src/main/java/uk/ac/manchester/tornado/runtime/interpreter/TornadoVMInterpreter.java

During interpreter warm-up, bytecode execution should not be logged. However, a check was missing for the bytecode header, causing only the header to be logged while the rest of the bytecodes were properly suppressed. This resulted in misleading and incomplete output logs.
**Before this fix:**
The logs would show duplicate headers without the corresponding bytecodes:
```bash
Interpreter instance running bytecodes for:   [NVIDIA CUDA] -- NVIDIA GeForce RTX 3070 Running in thread:  main <--- This header shouldn't appear during warm-up!
Interpreter instance running bytecodes for:   [NVIDIA CUDA] -- NVIDIA GeForce RTX 3070 Running in thread:  main
bc:  ALLOC uk.ac.manchester.tornado.api.types.arrays.IntArray@6ebd78d1 on   [NVIDIA CUDA] -- NVIDIA GeForce RTX 3070 , size=88, batchSize=0
bc: …
```

[nit] Avoid bytecode logging for header bytecode  during VM warm-up.

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLCompilationResultBuilder.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/compiler/PTXCompilationResultBuilder.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/compiler/SPIRVCompilationResultBuilder.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/ComputeTests.java

This PR fixes an issue with the scheduling of true branches. The logic to prioritise true branches was applied for all `IfNode` nodes, however, the rescheduling is only necessary if the `IfNode` is associated with a condition (for instance if there is a `break` or a `return` in the code). In this PR, a check is performed to ensure that the `IfNode` is not associated with a `LoopBegin` node (to evaluate the loop bounds) and rather it is generated due to a condition in the code, and only then it applies the logic to reschedule the necessary branches. 
Run 
`tornado-test -V uk.ac.manchester.tornado.unittests.compute.ComputeTests#testGroupedQueryAttention `
and 
`make …

Apply rescheduling of true branches only for conditions

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/phases/InverseSquareRootPhase.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/graal/phases/InverseSquareRootPhase.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/phases/InverseSquareRootPhase.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/math/TestMath.java

It seems that at some point something changed in the IR level and the ``InverseSquareRootPhase`` does not capture all patterns in the IR level, so it doesn't not properly apply the optimization to replace ``1/sqrt(x)`` with a native function for ``rsqrt(x)``.
Input code:
```java
public static void testInverseSquareRoot(DoubleArray a) {
for (@Parallel int i = 0; i < a.getSize(); i++) {
// This pattern (1.0 / Math.sqrt(x)) should be recognized and optimized to rsqrt(x)
a.set(i, 1.0 / TornadoMath.sqrt(a.get(i)));
}
}
```
```bash
tornado-test --printKernel -V uk.ac.manchester.tornado.unittests.math.TestMath#testOptimizedInverseSquareRoot
```
Before the fix:
```c++ …
```

[compiler] Fix 1.0/sqrt(x) replacement with native rsqrt(x) function

---

tornado-assembly/src/bin/tornado-test
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/compute/TransformerKernelsTest.java

This PR aims to replace #593. It contains a set of unit-tests to stress code gen of TornadoVM for kernel  used for a transformer architecture. 
Relative tests from #593 will be moved here. 
```bash
tornado-test -V uk.ac.manchester.tornado.unittests.compute.TransformerKernelsTest
```

Add unit tests for Transformer Compute Kernels expressed with a mix of KernelContextApi and `@Paralllel` API

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/scheduler/OCLKernelScheduler.java
tornado-drivers/ptx/src/main/java/uk/ac/manchester/tornado/drivers/ptx/PTXDeviceContext.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/SPIRVLevelZeroInstalledCode.java
tornado-drivers/spirv/src/main/java/uk/ac/manchester/tornado/drivers/spirv/graal/SPIRVOCLInstalledCode.java

This PR provides a fix for a bug that was spotted on `macOS` systems. When profiling with the TornadoVM profiler was enabled, the system was trying to read metrics from the UPS system. However, this should not be enabled if the flag for UPS reading is not enabled (i.e., if the `-Dtornado.ups.ip` is empty).
This PR adds relevant conditions to perform this check.
Provide instructions about how to test the new patch. 
```bash
make BACKEND=opencl && make fast-tests
make BACKEND=ptx && make fast-tests
make BACKEND=spirv && make fast-tests
```

[fix] Added guard conditions for UPS metrics when profiling across all backends

---

tornado-drivers/opencl/src/main/java/uk/ac/manchester/tornado/drivers/opencl/graal/compiler/OCLBlockVisitor.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/codegen/CodeGenTest.java

This PR addressed the code generation error reported in the issue #680.  In case there is a merge block two blocks above the `LoopEnd` block which is being examined by the `closeScope`, the rest of the loop exit points are checked. If there is only one loop exit point, the code in the PR checks if the only `LoopExit` node is followed by and `IfNode`, indicating nesting.  Since, in case of nesting, the `LoopExit` node is not expected to close the loop associated with it, the only other point which can close the loop is the `LoopEnd` block examined by the `closeScope`. Therefore, if this is the case, we proceed by closing the loop. 
Kfusion, TornadoVM-Raytracer and the unittests have all been checked and are not breaking with this fix. 
Mark the OS …

Fix closing bracket for flash attention

---

tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/codegen/CodeGenTest.java

This PR marks the unittest `uk.ac.manchester.tornado.unittests.codegen.CodeGenTest#testFlashAttention` as unsupported for SPIR-V, as its functionality is not currently implemented for this backend. 
```
tornado-test -V uk.ac.manchester.tornado.unittests.codegen.CodeGenTest#testFlashAttention
```

Mark Flash Attention Unittest Unsupported for SPIR-V

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/TornadoExecutor.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/warmup/TestWarmUp.java

Fix state after warmup 
The problem was that we need to update the `last to execute` graph after the execution plan runs, even after warmup. 
```bash
tornado-test -V --live uk.ac.manchester.tornado.unittests.warmup.TestWarmUp
```

[fix] Fix state after warmup phase

---

pom.xml
tornado-unittests/README.md
tornado-unittests/pom.xml
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/foundation/FoundationTestSuite.java

Added in unit-test package the option to run tests directly from mvn
```bash 
mvn exec:exec 
or for single class:
mvn exec:exec -Dtest.class=uk.ac.manchester.tornado.unittests.foundation.TestIntegers
```
```bash
Expected output:
╰─cmd ➜ mvn test -Dtest.class=uk.ac.manchester.tornado.unittests.foundation.TestIntegers
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< tornado:tornado-unittests >----------------------
[INFO] Building tornado-unittests 1.1.2-dev
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- buildnumber:1.4:create (default) @ tornado-unittests ---
[INFO] …
```

Add `mvn test` configuration to ease unit-testing when porting TornadoVM to third-party projects

---

tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/ByteArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/CharArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/DoubleArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/FloatArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/HalfFloatArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/IntArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/LongArray.java
tornado-api/src/main/java/uk/ac/manchester/tornado/api/types/arrays/ShortArray.java
tornado-unittests/src/main/java/uk/ac/manchester/tornado/unittests/arrays/TestLargeArrays.java

Fix integer overflow in TornadoNativeArray implementations that caused `IllegalArgumentException` when allocating large arrays. The issue occurred when calculating `segmentByteSize` using integer arithmetic, causing overflow for arrays requiring more than ~2GB of memory.
When creating large arrays (e.g., FloatArray with ~>540M elements), the calculation `numberOfElements * ELEMENT_BYTES + arrayHeaderSize` would overflow the integer range, resulting in negative values being passed to `Arena.allocate()`. This caused the following exception:
```java
Exception in thread "main" java.lang.IllegalArgumentException: Invalid allocation size : -1805647848
at java.base/jdk.internal.foreign.Utils.checkAllocationSizeAndAlign(Utils.java:206)
at …
```

[fix]  Integer overflow in TornadoNativeArray implementations that caused `IllegalArgumentException` when allocating large arrays
